export const screens = {
  s0: {
    brand: null,
    title: '어느 브랜드가 궁금해?',
    sub: '브랜드를 선택하면 핵심만 빠르게 파고듭니다',
    breadcrumb: null,
    cards: [
      {
        title: '교촌치킨',
        hint: '업계 1위 · 간장치킨 강자',
        val: '업계 1위',
        valColor: 'green',
        row1Val: '가맹점 수 1,300+',
        row1Label: '업계 최다 · 간장·허니 시리즈 강세',
        tags: [
          { label: '브랜드 1위', type: 'ok' },
          { label: '가맹비 높음', type: 'warn' },
          { label: '자금 2억+', type: 'warn' },
        ],
        text: '브랜드 파워 최강. 초기 투자금이 가장 높고, 본사 통제가 강한 편.',
        qBtn: { label: '교촌 자세히 보기 →', target: 'sgyo0' },
      },
      {
        title: '비비큐(BBQ)',
        hint: '업계 2위 · 황금올리브치킨',
        val: '업계 2위',
        valColor: 'green',
        row1Val: '가맹점 수 1,500+',
        row1Label: '해외 진출 · 프리미엄 포지셔닝',
        tags: [
          { label: '브랜드 2위', type: 'ok' },
          { label: '가격 프리미엄', type: 'neu' },
          { label: '로열티 부담', type: 'warn' },
        ],
        text: '글로벌 브랜드 이미지. 단가가 높아 객단가 유리하나 가격 저항도 있음.',
        qBtn: { label: 'BBQ 자세히 보기 →', target: 'sbbq0' },
      },
      {
        title: 'BHC치킨',
        hint: '업계 3위 · 뿌링클 강세',
        val: '업계 3위',
        valColor: 'yellow',
        row1Val: '가맹점 수 1,700+',
        row1Label: '뿌링클·맛초킹 · 배달 강세',
        tags: [
          { label: '브랜드 3위', type: 'neu' },
          { label: '자금 1.5억+', type: 'warn' },
          { label: '초보 가능', type: 'ok' },
        ],
        text: '시스템화 잘 돼있어 초보 창업자에게 진입 장벽 낮은 편.',
        qBtn: { label: 'BHC 자세히 보기 →', target: 'sbhc0' },
      },
      {
        title: '푸라닭치킨',
        hint: '중견 브랜드 · 허브치킨',
        val: '소자본 가능',
        valColor: 'green',
        row1Val: '가맹점 수 500+',
        row1Label: '허브시리즈 · 소규모 매장 가능',
        tags: [
          { label: '초기비용 낮음', type: 'ok' },
          { label: '브랜드 인지도↓', type: 'warn' },
          { label: '소자본 창업', type: 'ok' },
        ],
        text: '초기 투자 부담이 상대적으로 낮아 소자본 창업자에게 주목받는 브랜드.',
        qBtn: { label: '푸라닭 자세히 보기 →', target: 'spura0' },
      },
    ],
  },
  sbhc0: {
    brand: 'BHC 치킨',
    title: '뭐가 궁금해?',
    sub: '핵심만 빠르게 파고드세요',
    breadcrumb: null,
    cards: [
      {
        title: '해볼 만할까?',
        hint: '솔직한 한 줄 평가',
        val: '중상',
        valColor: 'yellow',
        row1Val: '종합 평가: 중상',
        row1Label: '초보 진입 가능 · 브랜드 3위 · 자금 부담 큼',
        tags: [
          { label: '초보자 가능', type: 'ok' },
          { label: '자금 1.5억+', type: 'warn' },
          { label: '브랜드 3위', type: 'neu' },
        ],
        text: '시스템화 잘 돼있어 배우기 쉽지만, 준비금 2억 미만이면 3개월 위기.',
        qBtn: { label: '3개월 안에 위기 온다는데, 진짜야? →', target: 's1' },
      },
      {
        title: '얼마 드나?',
        hint: '초기 투자 현실적으로',
        val: '1억 5천',
        valColor: 'red',
        row1Val: '총 1억 5,000만원',
        row1Label: '보증금 포함 시 최대 2억',
        tags: [
          { label: '가맹비 900만', type: 'warn' },
          { label: '인테리어 6.5천', type: 'warn' },
          { label: '예비금 별도', type: 'warn' },
        ],
        text: '공개 금액 외 보증금·예비금 3천 추가. 인테리어 본사 지정업체 강제.',
        qBtn: { label: '1억 5천인데 왜 2억이 필요하다고? →', target: 's5' },
      },
      {
        title: '얼마 남나?',
        hint: '한 달 실제 순이익',
        val: '약 280만',
        valColor: 'yellow',
        row1Val: '월 순이익 280만원',
        row1Label: '매출 1,200만 · 직원 1명 기준',
        tags: [
          { label: '재료비 -456만', type: 'warn' },
          { label: '인건비 -250만', type: 'warn' },
          { label: '임대료 -150만', type: 'warn' },
        ],
        text: '재료비 38%는 절감 불가 고정 구조. 직원 2명이면 100만대로 급락.',
        qBtn: { label: '열심히 해도 월 280이 전부야? →', target: 's9' },
      },
      {
        title: '어디서 망하나?',
        hint: '폐업 패턴 분석',
        val: '입지 1위',
        valColor: 'red',
        row1Val: '입지 실패 38%',
        row1Label: '오픈 후 3~6개월이 최대 위험',
        tags: [
          { label: '입지 38%', type: 'warn' },
          { label: '자금 31%', type: 'warn' },
          { label: '본사갈등 18%', type: 'neu' },
        ],
        text: '배달 상권인데 홀 인테리어로 갔다가 망한 케이스 다수.',
        qBtn: { label: '10명 중 3명이 망한다고? →', target: 's13' },
      },
    ],
  },
  s1: {
    brand: null,
    title: '해볼 만할까?',
    sub: '4가지 핵심으로 파악',
    breadcrumb: ['BHC', '해볼 만할까?'],
    cards: [
      {
        title: '브랜드 파워',
        hint: '치킨 시장 인지도',
        val: '상위 3위',
        valColor: 'green',
        row1Val: '인지도 98%',
        row1Label: '재방문율 62% · 배달앱 상위 5%',
        tags: [
          { label: '자연 집객 가능', type: 'ok' },
          { label: '로열티 2~3%', type: 'warn' },
        ],
        text: 'TV 광고 연 200억+ 투자. 오픈 초기 집객 빠름.',
        qBtn: { label: '브랜드 좋은데 왜 30%가 망해? →', target: 's13' },
      },
      {
        title: '초보자 난이도',
        hint: '시스템화 수준',
        val: '낮음',
        valColor: 'green',
        row1Val: '교육 3주 후 운영',
        row1Label: '매뉴얼 완성도 상',
        tags: [
          { label: '레시피 표준화', type: 'ok' },
          { label: '1인 운영 불가', type: 'warn' },
        ],
        text: '3주 교육 후 운영 가능. 단 1인은 물리적으로 불가.',
        qBtn: { label: '쉽다더니 왜 혼자는 못 하나? →', target: 's9' },
      },
      {
        title: '경쟁 강도',
        hint: '주변 밀집도',
        val: '높음',
        valColor: 'red',
        row1Val: '반경 500m 내 4.2개',
        row1Label: '치킨집 전국 8.7만개',
        tags: [
          { label: '동일브랜드 500m 보호', type: 'ok' },
          { label: '타브랜드 무제한', type: 'warn' },
        ],
        text: '같은 BHC는 500m 보호. 교촌·BBQ는 바로 옆도 가능.',
        qBtn: { label: '치킨집이 편의점보다 많다고? →', target: 's13' },
      },
      {
        title: '폐업 위험도',
        hint: '업계 통계 기반',
        val: '주의 필요',
        valColor: 'red',
        row1Val: '3년 내 폐업률 30%',
        row1Label: '오픈 6개월이 최대 위험',
        tags: [
          { label: '입지 실패 1위', type: 'warn' },
          { label: '자금 소진 2위', type: 'warn' },
        ],
        text: '사전 준비가 생존을 결정. 예비금 3천, 유동인구 3회 조사 최소.',
        qBtn: { label: '어디서 가장 많이 걸려서 망하나? →', target: 's13' },
      },
    ],
  },
  s5: {
    brand: null,
    title: '얼마 드나?',
    sub: '총 1억 5천 ~ 최대 2억',
    breadcrumb: ['BHC', '얼마 드나?'],
    cards: [
      {
        title: '가맹비',
        hint: '계약 시 일시납',
        val: '900만원',
        valColor: 'yellow',
        row1Val: '900만원 일시납',
        row1Label: '5년 계약 · 갱신 시 재납부',
        tags: [
          { label: '교촌보다 100만 저렴', type: 'neu' },
          { label: '환불 조건 까다로움', type: 'warn' },
        ],
        text: '1개월 내 일부 환불만 가능. 서명 전 특약 조항 필수 확인.',
        qBtn: { label: '계약 취소하면 돈 돌려받을 수 있어? →', target: 's13' },
      },
      {
        title: '인테리어',
        hint: '본사 지정업체 강제',
        val: '6,500만원',
        valColor: 'red',
        row1Val: '평당 약 325만원',
        row1Label: '20평 기준 · 5년마다 리모델링',
        tags: [
          { label: '본사 마진 20~30%', type: 'warn' },
          { label: '직접 업체 불가', type: 'warn' },
        ],
        text: '일반 인테리어 대비 과도하게 비쌈. 5년 후 리모델링 또 발생.',
        qBtn: { label: '6,500에 본사 마진 30%가 포함됐다고? →', target: 's13' },
      },
      {
        title: '장비/설비',
        hint: '주방 장비 일체',
        val: '4,800만원',
        valColor: 'red',
        row1Val: '4,800만원',
        row1Label: '튀김기·냉장·POS 포함',
        tags: [
          { label: '튀김기 3년 교체', type: 'warn' },
          { label: 'POS 300만', type: 'neu' },
        ],
        text: '튀김기 1,200만이 핵심. 3년 후 교체 비용 또 발생 예정.',
        qBtn: { label: '3년마다 또 수천만이 나간다고? →', target: 's9' },
      },
      {
        title: '숨겨진 비용',
        hint: '보증금 + 예비금',
        val: '+5천만 이상',
        valColor: 'red',
        row1Val: '최소 5,500만 추가',
        row1Label: '공개 금액 외 별도',
        tags: [
          { label: '보증금 2,500만~', type: 'warn' },
          { label: '예비금 3,000만', type: 'warn' },
        ],
        text: '공개 금액만 준비하면 오픈 3개월 내 자금 부족 위기.',
        qBtn: { label: '돈 모자라면 정확히 어느 순간 망해? →', target: 's13' },
      },
    ],
  },
  s9: {
    brand: null,
    title: '얼마 남나?',
    sub: '월 순이익 약 280만 (20평·직원1명)',
    breadcrumb: ['BHC', '얼마 남나?'],
    cards: [
      {
        title: '재료비',
        hint: '매출의 고정 비율',
        val: '-456만원',
        valColor: 'red',
        row1Val: '매출의 38% 고정',
        row1Label: '본사 공급 85% · 절감 불가',
        tags: [
          { label: '절감 여지 없음', type: 'warn' },
          { label: '매출 줄어도 고정', type: 'warn' },
        ],
        text: '본사 공급 85%. 닭고기 단가 마리당 4,200원 고정.',
        qBtn: { label: '본사가 단가 올리면 내가 다 떠안아? →', target: 's13' },
      },
      {
        title: '인건비',
        hint: '직원 1명 기준',
        val: '-250만원',
        valColor: 'red',
        row1Val: '250만원 기본',
        row1Label: '주말 알바 +80만 추가 가능',
        tags: [
          { label: '1인 운영 불가', type: 'warn' },
          { label: '매년 상승', type: 'warn' },
        ],
        text: '최저임금 인상으로 매년 오르는 구조. 주말 알바 포함 시 330만 넘을 수 있음.',
        qBtn: { label: '혼자 다 하면 1~2년 안에 번아웃 온다고? →', target: 's13' },
      },
      {
        title: '임대료',
        hint: '20평 평균',
        val: '-150만원',
        valColor: 'yellow',
        row1Val: '평균 150만원',
        row1Label: '상권에 따라 50~500만 차이',
        tags: [
          { label: '200만 되면 반토막', type: 'warn' },
          { label: '권리금 별도', type: 'warn' },
        ],
        text: '임대료는 계약 후 조정 불가. 손익분기 매출 1,050만 기준.',
        qBtn: { label: '임대 50만 차이가 순이익을 반으로 만든다고? →', target: 's13' },
      },
      {
        title: '실제 순이익',
        hint: '모든 비용 제외 후',
        val: '약 280만원',
        valColor: 'yellow',
        row1Val: '약 280만원',
        row1Label: '매출 1,200만 · 직원 1명 기준',
        tags: [
          { label: '직원 2명 → 100만대', type: 'warn' },
          { label: '매출 1,500만 → 420만', type: 'neu' },
        ],
        text: '매출 200만만 더 올리면 순이익 50% 상승. 배달 비율이 핵심.',
        qBtn: { label: '직원 한 명 더 쓰면 남는 게 없다고? →', target: 's13' },
      },
    ],
  },
  s13: {
    brand: null,
    title: '어디서 망하나?',
    sub: '오픈 6개월이 가장 위험한 구간',
    breadcrumb: ['BHC', '어디서 망하나?'],
    cards: [
      {
        title: '입지 실패',
        hint: '폐업 원인 1위',
        val: '38%',
        valColor: 'red',
        row1Val: '폐업의 38%',
        row1Label: '사전 조사가 생존을 결정',
        tags: [
          { label: '배달vs홀 미스매치', type: 'warn' },
          { label: '조사 최소 3회', type: 'warn' },
        ],
        text: '배달 상권인데 홀 인테리어. 평일·주말·저녁 유동인구 직접 조사 필수.',
        qBtn: { label: '오픈하고 나면 입지는 못 바꾼다고? →', target: 's1' },
      },
      {
        title: '자금 소진',
        hint: '초기 운영 위기',
        val: '31%',
        valColor: 'red',
        row1Val: '오픈 3개월차 최대 위험',
        row1Label: '오픈 버프 끝나는 시점',
        tags: [
          { label: '예비금 3천 필수', type: 'warn' },
          { label: '대출이자 포함 계획', type: 'warn' },
        ],
        text: '손익분기점 보통 4~6개월. 예비금 없으면 빠르게 악화.',
        qBtn: { label: '3개월 버티는 데 돈이 얼마나 필요해? →', target: 's5' },
      },
      {
        title: '본사 갈등',
        hint: '계약 분쟁',
        val: '18%',
        valColor: 'yellow',
        row1Val: '폐업의 18%',
        row1Label: '계약서 안 보면 당함',
        tags: [
          { label: '단가 연 2~5% 강제 인상', type: 'warn' },
          { label: '해지 조건 까다로움', type: 'warn' },
        ],
        text: '메뉴 강제 변경, 단가 인상 거부 불가. 해지 시 위약금 수천만.',
        qBtn: { label: '그만두고 싶어도 못 나온다고? →', target: 's5' },
      },
      {
        title: '번아웃 폐업',
        hint: '체력·정신 소모',
        val: '13%',
        valColor: 'yellow',
        row1Val: '폐업의 13%',
        row1Label: '주 7일 장시간 노동',
        tags: [
          { label: '1인 운영 시 고위험', type: 'warn' },
          { label: '1~2년 내 한계', type: 'neu' },
        ],
        text: '인력 계획 없으면 1~2년 내 체력·정신 한계 도달.',
        qBtn: { label: '월 280 벌려고 주 7일 일하는 거 맞아? →', target: 's9' },
      },
    ],
  },
  sgyo0: {
    brand: '교촌치킨',
    title: '뭐가 궁금해?',
    sub: '핵심만 빠르게 파고드세요',
    breadcrumb: null,
    cards: [
      {
        title: '해볼 만할까?',
        hint: '솔직한 한 줄 평가',
        val: '중상',
        valColor: 'yellow',
        row1Val: '종합 평가: 중상',
        row1Label: '브랜드 1위 · 초기비용 최고 · 본사 통제 강함',
        tags: [
          { label: '브랜드 1위', type: 'ok' },
          { label: '자금 2억+', type: 'warn' },
          { label: '본사 통제 강함', type: 'warn' },
        ],
        text: '브랜드 파워는 업계 최강이나 초기 투자금 부담이 크고 본사 규정이 엄격한 편.',
        qBtn: { label: '브랜드 1위인데 왜 통제가 강하다고? →', target: 'sgyo1' },
      },
      {
        title: '얼마 드나?',
        hint: '초기 투자 현실적으로',
        val: '2억 이상',
        valColor: 'red',
        row1Val: '총 2억~2.5억원',
        row1Label: '보증금·예비금 포함 시 최대 2.5억',
        tags: [
          { label: '가맹비 1,000만', type: 'warn' },
          { label: '인테리어 8천+', type: 'warn' },
          { label: '예비금 별도', type: 'warn' },
        ],
        text: '교촌은 3대 브랜드 중 초기 투자비가 가장 높음. 인테리어 단가 업계 최고 수준.',
        qBtn: { label: '왜 교촌이 가장 비싼 거야? →', target: 'sgyo5' },
      },
      {
        title: '얼마 남나?',
        hint: '한 달 실제 순이익',
        val: '약 320만',
        valColor: 'yellow',
        row1Val: '월 순이익 320만원',
        row1Label: '매출 1,300만 · 직원 1명 기준',
        tags: [
          { label: '재료비 -494만', type: 'warn' },
          { label: '인건비 -250만', type: 'warn' },
          { label: '임대료 -150만', type: 'warn' },
        ],
        text: '객단가가 높아 매출 규모는 크지만 재료비·로열티 비율도 높아 실질 마진은 제한적.',
        qBtn: { label: '객단가 높은데 왜 순이익이 별로야? →', target: 'sgyo9' },
      },
      {
        title: '어디서 망하나?',
        hint: '폐업 패턴 분석',
        val: '자금 1위',
        valColor: 'red',
        row1Val: '자금 소진 35%',
        row1Label: '높은 초기비용이 가장 큰 리스크',
        tags: [
          { label: '자금 35%', type: 'warn' },
          { label: '입지 33%', type: 'warn' },
          { label: '본사갈등 20%', type: 'neu' },
        ],
        text: '초기 투자금이 크기 때문에 손익분기점 도달 전 자금 소진이 가장 큰 위험 요인.',
        qBtn: { label: '2억 넘게 쓰고 망하면 얼마나 날아가? →', target: 'sgyo13' },
      },
    ],
  },
  sgyo1: {
    brand: null,
    title: '해볼 만할까?',
    sub: '4가지 핵심으로 파악',
    breadcrumb: ['교촌', '해볼 만할까?'],
    cards: [
      {
        title: '브랜드 파워',
        hint: '치킨 시장 인지도',
        val: '업계 1위',
        valColor: 'green',
        row1Val: '인지도 99%',
        row1Label: '재방문율 68% · 배달앱 상위 3%',
        tags: [
          { label: '자연 집객 최강', type: 'ok' },
          { label: '로열티 2%', type: 'warn' },
        ],
        text: '간장·허니콤보 시리즈로 고정 팬층 두터움. 오픈 초기 집객 속도 3사 중 가장 빠름.',
        qBtn: { label: '브랜드 최강인데 왜 비용도 최강이야? →', target: 'sgyo5' },
      },
      {
        title: '초보자 난이도',
        hint: '시스템화 수준',
        val: '보통',
        valColor: 'yellow',
        row1Val: '교육 4주 후 운영',
        row1Label: '메뉴 복잡도 높음',
        tags: [
          { label: '레시피 표준화', type: 'ok' },
          { label: '메뉴 수 많음', type: 'warn' },
          { label: '1인 운영 불가', type: 'warn' },
        ],
        text: '간장소스 계열 메뉴가 많아 BHC보다 숙련 시간이 더 걸림. 4주 교육 필수.',
        qBtn: { label: '메뉴 많으면 운영이 얼마나 힘들어? →', target: 'sgyo9' },
      },
      {
        title: '경쟁 강도',
        hint: '주변 밀집도',
        val: '높음',
        valColor: 'red',
        row1Val: '반경 500m 내 4.8개',
        row1Label: '치킨집 전국 8.7만개',
        tags: [
          { label: '동일브랜드 500m 보호', type: 'ok' },
          { label: '타브랜드 무제한', type: 'warn' },
        ],
        text: '교촌 간 500m 보호 존재. 그러나 BBQ·BHC·푸라닭은 바로 옆 입점 가능.',
        qBtn: { label: '보호구역 있어도 경쟁 심하다고? →', target: 'sgyo13' },
      },
      {
        title: '폐업 위험도',
        hint: '업계 통계 기반',
        val: '주의 필요',
        valColor: 'red',
        row1Val: '3년 내 폐업률 28%',
        row1Label: '오픈 6개월이 최대 위험',
        tags: [
          { label: '자금 소진 1위', type: 'warn' },
          { label: '입지 실패 2위', type: 'warn' },
        ],
        text: '초기 투자금이 크기 때문에 손익분기 전에 자금 소진되는 케이스 다수.',
        qBtn: { label: '어디서 가장 많이 걸려서 망하나? →', target: 'sgyo13' },
      },
    ],
  },
  sgyo5: {
    brand: null,
    title: '얼마 드나?',
    sub: '총 2억 ~ 최대 2억 5천',
    breadcrumb: ['교촌', '얼마 드나?'],
    cards: [
      {
        title: '가맹비',
        hint: '계약 시 일시납',
        val: '1,000만원',
        valColor: 'yellow',
        row1Val: '1,000만원 일시납',
        row1Label: '5년 계약 · 갱신 시 재납부',
        tags: [
          { label: 'BHC보다 100만 비쌈', type: 'warn' },
          { label: '환불 조건 까다로움', type: 'warn' },
        ],
        text: '3대 브랜드 중 가맹비 중간 수준. 단 교육비 200만 별도 청구.',
        qBtn: { label: '교육비가 왜 따로 있어? →', target: 'sgyo13' },
      },
      {
        title: '인테리어',
        hint: '본사 지정업체 강제',
        val: '7,000만원',
        valColor: 'red',
        row1Val: '평당 약 350만원',
        row1Label: '20평 기준 · 5년마다 리모델링',
        tags: [
          { label: '본사 마진 25~35%', type: 'warn' },
          { label: '직접 업체 불가', type: 'warn' },
        ],
        text: 'BHC보다 500만 이상 비쌈. 브랜드 아이덴티티 유지 명목으로 업체 선택 불가.',
        qBtn: { label: '왜 직접 업체 쓰면 안 돼? →', target: 'sgyo13' },
      },
      {
        title: '장비/설비',
        hint: '주방 장비 일체',
        val: '5,000만원',
        valColor: 'red',
        row1Val: '5,000만원',
        row1Label: '튀김기·냉장·POS 포함',
        tags: [
          { label: '튀김기 3년 교체', type: 'warn' },
          { label: 'POS 350만', type: 'neu' },
        ],
        text: '소스 전용 냉장설비 추가로 BHC 대비 200만 높음. 3년 후 교체비 또 발생.',
        qBtn: { label: '3년마다 또 수천만이 나간다고? →', target: 'sgyo9' },
      },
      {
        title: '숨겨진 비용',
        hint: '보증금 + 예비금',
        val: '+5천 5백만+',
        valColor: 'red',
        row1Val: '최소 5,500만 추가',
        row1Label: '공개 금액 외 별도',
        tags: [
          { label: '보증금 2,500만~', type: 'warn' },
          { label: '예비금 3,000만', type: 'warn' },
        ],
        text: '공개 금액만 보고 2억 준비했다가 오픈 후 3개월에 자금 위기 오는 패턴.',
        qBtn: { label: '돈 모자라면 정확히 어느 순간 망해? →', target: 'sgyo13' },
      },
    ],
  },
  sgyo9: {
    brand: null,
    title: '얼마 남나?',
    sub: '월 순이익 약 320만 (20평·직원1명)',
    breadcrumb: ['교촌', '얼마 남나?'],
    cards: [
      {
        title: '재료비',
        hint: '매출의 고정 비율',
        val: '-520만원',
        valColor: 'red',
        row1Val: '매출의 40% 고정',
        row1Label: '본사 공급 90% · 절감 불가',
        tags: [
          { label: '절감 여지 없음', type: 'warn' },
          { label: '매출 줄어도 고정', type: 'warn' },
        ],
        text: '본사 공급 비율 90%로 BHC보다 높음. 닭고기 단가 마리당 4,500원 고정.',
        qBtn: { label: '본사 공급 90%면 내 마음대로 못 해? →', target: 'sgyo13' },
      },
      {
        title: '인건비',
        hint: '직원 1명 기준',
        val: '-250만원',
        valColor: 'red',
        row1Val: '250만원 기본',
        row1Label: '주말 알바 +80만 추가 가능',
        tags: [
          { label: '1인 운영 불가', type: 'warn' },
          { label: '매년 상승', type: 'warn' },
        ],
        text: '메뉴 복잡도가 높아 숙련 직원이 필요. 알바 교체 시 재교육 비용도 발생.',
        qBtn: { label: '메뉴 복잡해서 알바 구하기 어렵다고? →', target: 'sgyo13' },
      },
      {
        title: '임대료',
        hint: '20평 평균',
        val: '-150만원',
        valColor: 'yellow',
        row1Val: '평균 150만원',
        row1Label: '상권에 따라 50~500만 차이',
        tags: [
          { label: '200만 되면 반토막', type: 'warn' },
          { label: '권리금 별도', type: 'warn' },
        ],
        text: '브랜드 파워로 A급 상권 입점 욕구 높지만 임대료 오르면 수익 급감.',
        qBtn: { label: '좋은 상권 들어가면 임대료가 얼마야? →', target: 'sgyo13' },
      },
      {
        title: '실제 순이익',
        hint: '모든 비용 제외 후',
        val: '약 320만원',
        valColor: 'yellow',
        row1Val: '약 320만원',
        row1Label: '매출 1,300만 · 직원 1명 기준',
        tags: [
          { label: '직원 2명 → 130만대', type: 'warn' },
          { label: '매출 1,600만 → 460만', type: 'neu' },
        ],
        text: '매출이 300만 오르면 순이익 44% 상승. 배달 비율·점심 매출 확보가 핵심.',
        qBtn: { label: '월 320이면 투자금 회수에 몇 년 걸려? →', target: 'sgyo5' },
      },
    ],
  },
  sgyo13: {
    brand: null,
    title: '어디서 망하나?',
    sub: '오픈 6개월이 가장 위험한 구간',
    breadcrumb: ['교촌', '어디서 망하나?'],
    cards: [
      {
        title: '자금 소진',
        hint: '폐업 원인 1위',
        val: '35%',
        valColor: 'red',
        row1Val: '폐업의 35%',
        row1Label: '높은 초기비용이 직격탄',
        tags: [
          { label: '예비금 3천 필수', type: 'warn' },
          { label: '손익분기 5~7개월', type: 'warn' },
        ],
        text: '2억+ 투자 후 손익분기 전에 예비금 소진. 대출이자까지 포함하면 빠르게 악화.',
        qBtn: { label: '손익분기까지 버티는 게 왜 이렇게 힘들어? →', target: 'sgyo5' },
      },
      {
        title: '입지 실패',
        hint: '폐업 원인 2위',
        val: '33%',
        valColor: 'red',
        row1Val: '폐업의 33%',
        row1Label: '사전 조사가 생존을 결정',
        tags: [
          { label: '배달vs홀 미스매치', type: 'warn' },
          { label: '조사 최소 3회', type: 'warn' },
        ],
        text: '교촌은 홀 매출 비중이 높아 유동인구 분석이 특히 중요. 배달 전용 상권에 홀 인테리어하면 망함.',
        qBtn: { label: '오픈하고 나면 입지는 못 바꾼다고? →', target: 'sgyo1' },
      },
      {
        title: '본사 갈등',
        hint: '계약 분쟁',
        val: '20%',
        valColor: 'yellow',
        row1Val: '폐업의 20%',
        row1Label: '계약서 안 보면 당함',
        tags: [
          { label: '단가 연 3~5% 강제 인상', type: 'warn' },
          { label: '메뉴 강제 변경', type: 'warn' },
        ],
        text: '본사 통제가 3사 중 가장 강함. 메뉴·가격·인테리어 모두 본사 결정. 거부 불가.',
        qBtn: { label: '그만두고 싶어도 못 나온다고? →', target: 'sgyo5' },
      },
      {
        title: '번아웃 폐업',
        hint: '체력·정신 소모',
        val: '12%',
        valColor: 'yellow',
        row1Val: '폐업의 12%',
        row1Label: '주 7일 장시간 노동',
        tags: [
          { label: '1인 운영 시 고위험', type: 'warn' },
          { label: '1~2년 내 한계', type: 'neu' },
        ],
        text: '메뉴 복잡도 높아 직원 없이 혼자 운영 시 BHC보다 체력 소모 큼.',
        qBtn: { label: '월 320 벌려고 주 7일 일하는 거 맞아? →', target: 'sgyo9' },
      },
    ],
  },
  sbbq0: {
    brand: '비비큐(BBQ)',
    title: '뭐가 궁금해?',
    sub: '핵심만 빠르게 파고드세요',
    breadcrumb: null,
    cards: [
      {
        title: '해볼 만할까?',
        hint: '솔직한 한 줄 평가',
        val: '중상',
        valColor: 'yellow',
        row1Val: '종합 평가: 중상',
        row1Label: '브랜드 2위 · 프리미엄 전략 · 초기비용 높음',
        tags: [
          { label: '브랜드 2위', type: 'ok' },
          { label: '자금 2억+', type: 'warn' },
          { label: '객단가 높음', type: 'neu' },
        ],
        text: '프리미엄 포지셔닝으로 객단가는 높지만 초기 투자와 로열티 부담이 큰 구조.',
        qBtn: { label: '프리미엄인데 왜 로열티가 부담이야? →', target: 'sbbq1' },
      },
      {
        title: '얼마 드나?',
        hint: '초기 투자 현실적으로',
        val: '2억 내외',
        valColor: 'red',
        row1Val: '총 1억 9천~2억 5천',
        row1Label: '보증금·예비금 포함 시 최대 2.5억',
        tags: [
          { label: '가맹비 1,500만', type: 'warn' },
          { label: '인테리어 9천+', type: 'warn' },
          { label: '예비금 별도', type: 'warn' },
        ],
        text: '3대 브랜드 중 가맹비 최고 수준. 인테리어도 프리미엄 기준 적용.',
        qBtn: { label: '가맹비 1,500만이면 얼마나 비싼 거야? →', target: 'sbbq5' },
      },
      {
        title: '얼마 남나?',
        hint: '한 달 실제 순이익',
        val: '약 340만',
        valColor: 'yellow',
        row1Val: '월 순이익 340만원',
        row1Label: '매출 1,400만 · 직원 1명 기준',
        tags: [
          { label: '재료비 -532만', type: 'warn' },
          { label: '인건비 -250만', type: 'warn' },
          { label: '로열티 -42만', type: 'warn' },
        ],
        text: '단가 높아 매출은 크지만 재료비·로열티 합산 비율이 높아 실수령은 생각보다 낮음.',
        qBtn: { label: '매출 1,400인데 순이익이 340뿐이야? →', target: 'sbbq9' },
      },
      {
        title: '어디서 망하나?',
        hint: '폐업 패턴 분석',
        val: '가격저항 1위',
        valColor: 'red',
        row1Val: '가격저항 32%',
        row1Label: '프리미엄 가격에 소비자 이탈',
        tags: [
          { label: '가격저항 32%', type: 'warn' },
          { label: '입지 31%', type: 'warn' },
          { label: '자금소진 25%', type: 'warn' },
        ],
        text: '경기 불황기에 프리미엄 가격 저항으로 매출 급감 리스크. 상권 선택이 핵심.',
        qBtn: { label: '비싼 치킨 안 팔리면 어떻게 돼? →', target: 'sbbq13' },
      },
    ],
  },
  spura0: {
    brand: '푸라닭치킨',
    title: '뭐가 궁금해?',
    sub: '핵심만 빠르게 파고드세요',
    breadcrumb: null,
    cards: [
      {
        title: '해볼 만할까?',
        hint: '솔직한 한 줄 평가',
        val: '중',
        valColor: 'yellow',
        row1Val: '종합 평가: 중',
        row1Label: '소자본 가능 · 인지도 낮음 · 틈새 전략',
        tags: [
          { label: '초기비용 낮음', type: 'ok' },
          { label: '브랜드 인지도↓', type: 'warn' },
          { label: '틈새 포지션', type: 'neu' },
        ],
        text: '소자본으로 시작 가능하지만 브랜드 자체 집객이 약해 마케팅 노력이 더 필요.',
        qBtn: { label: '인지도 낮으면 손님이 올까? →', target: 'spura1' },
      },
      {
        title: '얼마 드나?',
        hint: '초기 투자 현실적으로',
        val: '1억 내외',
        valColor: 'yellow',
        row1Val: '총 9천~1억 2천만원',
        row1Label: '3대 브랜드 대비 40% 저렴',
        tags: [
          { label: '가맹비 500만', type: 'ok' },
          { label: '인테리어 5천~', type: 'neu' },
          { label: '예비금 별도', type: 'warn' },
        ],
        text: '초기 투자 부담이 낮아 소자본 창업자에게 유리. 단 예비금은 필수.',
        qBtn: { label: '싸게 시작하면 나중에 더 드는 거 아냐? →', target: 'spura5' },
      },
      {
        title: '얼마 남나?',
        hint: '한 달 실제 순이익',
        val: '약 220만',
        valColor: 'yellow',
        row1Val: '월 순이익 220만원',
        row1Label: '매출 1,000만 · 직원 1명 기준',
        tags: [
          { label: '재료비 -380만', type: 'warn' },
          { label: '인건비 -250만', type: 'warn' },
          { label: '임대료 -120만', type: 'warn' },
        ],
        text: '매출 규모가 작아 절대 순이익은 낮은 편. 매출 확대가 수익의 핵심 변수.',
        qBtn: { label: '월 220만이면 너무 적은 거 아냐? →', target: 'spura9' },
      },
      {
        title: '어디서 망하나?',
        hint: '폐업 패턴 분석',
        val: '집객 1위',
        valColor: 'red',
        row1Val: '집객 부족 40%',
        row1Label: '브랜드 인지도 부족이 직격탄',
        tags: [
          { label: '집객부족 40%', type: 'warn' },
          { label: '입지 30%', type: 'warn' },
          { label: '자금소진 20%', type: 'warn' },
        ],
        text: '브랜드 파워가 약해 오픈 초기 집객을 본인이 만들어야 함. SNS·배달앱 마케팅 필수.',
        qBtn: { label: '브랜드 힘 없이 어떻게 손님을 모아? →', target: 'spura13' },
      },
    ],
  },
  sbbq1: {
    brand: null,
    title: '해볼 만할까?',
    sub: '4가지 핵심으로 파악',
    breadcrumb: ['BBQ', '해볼 만할까?'],
    cards: [
      {
        title: '브랜드 파워',
        hint: '치킨 시장 인지도',
        val: '업계 2위',
        valColor: 'green',
        row1Val: '인지도 97%',
        row1Label: '재방문율 60% · 해외 50개국 진출',
        tags: [
          { label: '프리미엄 이미지', type: 'ok' },
          { label: '로열티 2~3%', type: 'warn' },
        ],
        text: '황금올리브치킨으로 프리미엄 포지셔닝 성공. 단가가 높아 객단가 유리.',
        qBtn: { label: '프리미엄 브랜드인데 왜 30%가 망해? →', target: 'sbbq13' },
      },
      {
        title: '초보자 난이도',
        hint: '시스템화 수준',
        val: '낮음',
        valColor: 'green',
        row1Val: '교육 3주 후 운영',
        row1Label: '매뉴얼 완성도 상',
        tags: [
          { label: '레시피 표준화', type: 'ok' },
          { label: '1인 운영 불가', type: 'warn' },
        ],
        text: '3주 교육 후 운영 가능. 메뉴 수 적어 숙련이 빠른 편.',
        qBtn: { label: '쉽다더니 왜 혼자는 못 하나? →', target: 'sbbq9' },
      },
      {
        title: '경쟁 강도',
        hint: '주변 밀집도',
        val: '높음',
        valColor: 'red',
        row1Val: '반경 500m 내 4.5개',
        row1Label: '치킨집 전국 8.7만개',
        tags: [
          { label: '동일브랜드 500m 보호', type: 'ok' },
          { label: '타브랜드 무제한', type: 'warn' },
        ],
        text: '같은 BBQ는 500m 보호. 교촌·BHC는 바로 옆도 가능. 가격 경쟁 심함.',
        qBtn: { label: '비싼데 옆에 싼 치킨집 생기면? →', target: 'sbbq13' },
      },
      {
        title: '폐업 위험도',
        hint: '업계 통계 기반',
        val: '주의 필요',
        valColor: 'red',
        row1Val: '3년 내 폐업률 29%',
        row1Label: '오픈 6개월이 최대 위험',
        tags: [
          { label: '가격저항 1위', type: 'warn' },
          { label: '자금 소진 2위', type: 'warn' },
        ],
        text: '경기 불황기에 프리미엄 가격 저항이 가장 큰 리스크. 상권 선택이 생존 열쇠.',
        qBtn: { label: '어디서 가장 많이 걸려서 망하나? →', target: 'sbbq13' },
      },
    ],
  },
  sbbq5: {
    brand: null,
    title: '얼마 드나?',
    sub: '총 1억 9천 ~ 최대 2억 5천',
    breadcrumb: ['BBQ', '얼마 드나?'],
    cards: [
      {
        title: '가맹비',
        hint: '계약 시 일시납',
        val: '1,500만원',
        valColor: 'red',
        row1Val: '1,500만원 일시납',
        row1Label: '5년 계약 · 갱신 시 재납부',
        tags: [
          { label: '3사 중 가장 비쌈', type: 'warn' },
          { label: '환불 조건 까다로움', type: 'warn' },
        ],
        text: 'BHC보다 600만, 교촌보다 500만 비쌈. 계약 전 특약 조항 꼼꼼히 확인 필수.',
        qBtn: { label: '계약 취소하면 돈 돌려받을 수 있어? →', target: 'sbbq13' },
      },
      {
        title: '인테리어',
        hint: '본사 지정업체 강제',
        val: '9,000만원',
        valColor: 'red',
        row1Val: '평당 약 450만원',
        row1Label: '20평 기준 · 5년마다 리모델링',
        tags: [
          { label: '본사 마진 25~35%', type: 'warn' },
          { label: '직접 업체 불가', type: 'warn' },
        ],
        text: '3사 최고가 인테리어. 프리미엄 인테리어 콘셉트로 업체 변경 불가.',
        qBtn: { label: '9,000에 본사 마진이 포함됐다고? →', target: 'sbbq13' },
      },
      {
        title: '장비/설비',
        hint: '주방 장비 일체',
        val: '4,500만원',
        valColor: 'red',
        row1Val: '4,500만원',
        row1Label: '튀김기·냉장·POS 포함',
        tags: [
          { label: '튀김기 3년 교체', type: 'warn' },
          { label: 'POS 350만', type: 'neu' },
        ],
        text: '튀김기 1,200만이 핵심. 3년 후 교체 비용 별도 발생.',
        qBtn: { label: '3년마다 또 수천만이 나간다고? →', target: 'sbbq9' },
      },
      {
        title: '숨겨진 비용',
        hint: '보증금 + 예비금',
        val: '+5천만 이상',
        valColor: 'red',
        row1Val: '최소 5,500만 추가',
        row1Label: '공개 금액 외 별도',
        tags: [
          { label: '보증금 2,500만~', type: 'warn' },
          { label: '예비금 3,000만', type: 'warn' },
        ],
        text: '공개 금액만 준비하면 오픈 3개월 내 자금 부족. 총 2.5억 준비가 안전선.',
        qBtn: { label: '돈 모자라면 정확히 어느 순간 망해? →', target: 'sbbq13' },
      },
    ],
  },
  sbbq9: {
    brand: null,
    title: '얼마 남나?',
    sub: '월 순이익 약 340만 (20평·직원1명)',
    breadcrumb: ['BBQ', '얼마 남나?'],
    cards: [
      {
        title: '재료비',
        hint: '매출의 고정 비율',
        val: '-532만원',
        valColor: 'red',
        row1Val: '매출의 38% 고정',
        row1Label: '본사 공급 88% · 절감 불가',
        tags: [
          { label: '절감 여지 없음', type: 'warn' },
          { label: '매출 줄어도 고정', type: 'warn' },
        ],
        text: '본사 공급 비율 88%. 올리브유 등 고급 재료 사용으로 원가율이 높은 구조.',
        qBtn: { label: '본사가 단가 올리면 내가 다 떠안아? →', target: 'sbbq13' },
      },
      {
        title: '인건비',
        hint: '직원 1명 기준',
        val: '-250만원',
        valColor: 'red',
        row1Val: '250만원 기본',
        row1Label: '주말 알바 +80만 추가 가능',
        tags: [
          { label: '1인 운영 불가', type: 'warn' },
          { label: '매년 상승', type: 'warn' },
        ],
        text: '최저임금 인상으로 매년 오르는 구조. 주말 알바 포함 시 330만 넘을 수 있음.',
        qBtn: { label: '혼자 다 하면 1~2년 안에 번아웃 온다고? →', target: 'sbbq13' },
      },
      {
        title: '로열티',
        hint: '매출의 고정 비율',
        val: '-42만원',
        valColor: 'yellow',
        row1Val: '매출의 3% 고정',
        row1Label: '3사 중 로열티 최고',
        tags: [
          { label: '매출 올라도 비율 고정', type: 'warn' },
          { label: '분쟁 시 인상 가능', type: 'warn' },
        ],
        text: '3% 로열티는 BHC(2%)보다 부담 큼. 매출 2,000만 되면 로열티만 60만.',
        qBtn: { label: '로열티 3%가 얼마나 큰 차이야? →', target: 'sbbq5' },
      },
      {
        title: '실제 순이익',
        hint: '모든 비용 제외 후',
        val: '약 340만원',
        valColor: 'yellow',
        row1Val: '약 340만원',
        row1Label: '매출 1,400만 · 직원 1명 기준',
        tags: [
          { label: '직원 2명 → 120만대', type: 'warn' },
          { label: '매출 1,700만 → 480만', type: 'neu' },
        ],
        text: '객단가 높아 매출 확대 여지 있음. 단 경기 불황 시 프리미엄 저항으로 매출 급락 위험.',
        qBtn: { label: '불황 오면 매출이 얼마나 빠져? →', target: 'sbbq13' },
      },
    ],
  },
  sbbq13: {
    brand: null,
    title: '어디서 망하나?',
    sub: '오픈 6개월이 가장 위험한 구간',
    breadcrumb: ['BBQ', '어디서 망하나?'],
    cards: [
      {
        title: '가격 저항',
        hint: '폐업 원인 1위',
        val: '32%',
        valColor: 'red',
        row1Val: '폐업의 32%',
        row1Label: '프리미엄 가격에 소비자 이탈',
        tags: [
          { label: '경기 민감도 높음', type: 'warn' },
          { label: '상권 선택 핵심', type: 'warn' },
        ],
        text: '경기 불황기 BBQ 매출 감소율이 3사 중 가장 큼. 소득 높은 상권에서만 안정적.',
        qBtn: { label: '어떤 상권이 BBQ에 맞아? →', target: 'sbbq1' },
      },
      {
        title: '입지 실패',
        hint: '폐업 원인 2위',
        val: '31%',
        valColor: 'red',
        row1Val: '폐업의 31%',
        row1Label: '상권 소득 수준 미스매치',
        tags: [
          { label: '저소득 상권 위험', type: 'warn' },
          { label: '조사 최소 3회', type: 'warn' },
        ],
        text: '일반 치킨 상권에서 프리미엄 가격 판매 시 가격 저항으로 이탈. 상권 소득 수준 분석 필수.',
        qBtn: { label: '오픈하고 나면 입지는 못 바꾼다고? →', target: 'sbbq1' },
      },
      {
        title: '자금 소진',
        hint: '초기 운영 위기',
        val: '25%',
        valColor: 'red',
        row1Val: '오픈 3개월차 최대 위험',
        row1Label: '초기 투자비 회수 기간 길어짐',
        tags: [
          { label: '예비금 3천 필수', type: 'warn' },
          { label: '대출이자 포함 계획', type: 'warn' },
        ],
        text: '손익분기점 보통 5~7개월. 초기 투자비가 커서 BHC보다 손익분기 도달이 늦음.',
        qBtn: { label: '3개월 버티는 데 돈이 얼마나 필요해? →', target: 'sbbq5' },
      },
      {
        title: '본사 갈등',
        hint: '계약 분쟁',
        val: '12%',
        valColor: 'yellow',
        row1Val: '폐업의 12%',
        row1Label: '계약서 안 보면 당함',
        tags: [
          { label: '단가 연 2~4% 강제 인상', type: 'warn' },
          { label: '해지 조건 까다로움', type: 'warn' },
        ],
        text: '메뉴·가격 강제 변경, 거부 불가. 해지 시 위약금 수천만. 계약 전 법무 검토 권장.',
        qBtn: { label: '그만두고 싶어도 못 나온다고? →', target: 'sbbq5' },
      },
    ],
  },
  spura1: {
    brand: null,
    title: '해볼 만할까?',
    sub: '4가지 핵심으로 파악',
    breadcrumb: ['푸라닭', '해볼 만할까?'],
    cards: [
      {
        title: '브랜드 파워',
        hint: '치킨 시장 인지도',
        val: '중하위',
        valColor: 'yellow',
        row1Val: '인지도 60%',
        row1Label: '재방문율 55% · 허브치킨 마니아층',
        tags: [
          { label: '마니아층 존재', type: 'ok' },
          { label: '자연 집객 약함', type: 'warn' },
        ],
        text: '허브시리즈 팬층은 있지만 3대 브랜드 대비 인지도 낮아 직접 마케팅이 필수.',
        qBtn: { label: '인지도 낮으면 오픈 초기 어때? →', target: 'spura13' },
      },
      {
        title: '초보자 난이도',
        hint: '시스템화 수준',
        val: '낮음',
        valColor: 'green',
        row1Val: '교육 2~3주 후 운영',
        row1Label: '메뉴 단순 · 매뉴얼 완성도 중상',
        tags: [
          { label: '레시피 표준화', type: 'ok' },
          { label: '소규모 운영 가능', type: 'ok' },
        ],
        text: '메뉴 수 적고 조리 과정 단순해 초보 창업자가 빠르게 적응 가능.',
        qBtn: { label: '소규모로 혼자 운영할 수 있어? →', target: 'spura9' },
      },
      {
        title: '경쟁 강도',
        hint: '주변 밀집도',
        val: '높음',
        valColor: 'red',
        row1Val: '반경 500m 내 4.2개',
        row1Label: '치킨집 전국 8.7만개',
        tags: [
          { label: '동일브랜드 500m 보호', type: 'ok' },
          { label: '3대 브랜드와 경쟁', type: 'warn' },
        ],
        text: '3대 브랜드보다 인지도 낮아 경쟁 체감이 더 큼. 배달앱 상위 노출 전략 필수.',
        qBtn: { label: '브랜드 약한데 경쟁에서 살아남으려면? →', target: 'spura13' },
      },
      {
        title: '폐업 위험도',
        hint: '업계 통계 기반',
        val: '주의 필요',
        valColor: 'red',
        row1Val: '3년 내 폐업률 33%',
        row1Label: '집객 실패가 최대 위험',
        tags: [
          { label: '집객 부족 1위', type: 'warn' },
          { label: '입지 실패 2위', type: 'warn' },
        ],
        text: '브랜드 파워로 커버가 안 돼 오픈 초기 집객을 스스로 만들어야 하는 부담이 큼.',
        qBtn: { label: '어디서 가장 많이 걸려서 망하나? →', target: 'spura13' },
      },
    ],
  },
  spura5: {
    brand: null,
    title: '얼마 드나?',
    sub: '총 9천 ~ 최대 1억 2천',
    breadcrumb: ['푸라닭', '얼마 드나?'],
    cards: [
      {
        title: '가맹비',
        hint: '계약 시 일시납',
        val: '500만원',
        valColor: 'green',
        row1Val: '500만원 일시납',
        row1Label: '5년 계약 · 갱신 시 재납부',
        tags: [
          { label: 'BHC보다 400만 저렴', type: 'ok' },
          { label: '환불 조건 확인 필요', type: 'warn' },
        ],
        text: '3대 브랜드 대비 가맹비 부담 크게 낮음. 단 브랜드 지원도 상대적으로 적음.',
        qBtn: { label: '가맹비 싸면 지원도 적은 거야? →', target: 'spura1' },
      },
      {
        title: '인테리어',
        hint: '본사 지정업체 강제',
        val: '5,000만원',
        valColor: 'yellow',
        row1Val: '평당 약 250만원',
        row1Label: '20평 기준 · 5년마다 리모델링',
        tags: [
          { label: '3사보다 40% 저렴', type: 'ok' },
          { label: '직접 업체 불가', type: 'warn' },
        ],
        text: 'BHC(6,500만) 대비 1,500만 저렴. 단 직접 업체 사용은 불가.',
        qBtn: { label: '5년 후 리모델링 비용도 똑같이 나와? →', target: 'spura13' },
      },
      {
        title: '장비/설비',
        hint: '주방 장비 일체',
        val: '3,500만원',
        valColor: 'yellow',
        row1Val: '3,500만원',
        row1Label: '튀김기·냉장·POS 포함',
        tags: [
          { label: '튀김기 3년 교체', type: 'warn' },
          { label: 'POS 250만', type: 'neu' },
        ],
        text: '3대 브랜드 대비 장비 비용 낮음. 소규모 매장 특성상 장비 수도 적은 편.',
        qBtn: { label: '장비 싸면 품질도 다른 거야? →', target: 'spura1' },
      },
      {
        title: '숨겨진 비용',
        hint: '보증금 + 예비금',
        val: '+3천만 이상',
        valColor: 'yellow',
        row1Val: '최소 3,000만 추가',
        row1Label: '공개 금액 외 별도',
        tags: [
          { label: '보증금 1,500만~', type: 'warn' },
          { label: '예비금 2,000만', type: 'warn' },
        ],
        text: '초기 투자가 낮아도 예비금은 반드시 확보. 공개 금액만 보면 3개월 내 위기.',
        qBtn: { label: '1억 미만으로 진짜 창업 가능해? →', target: 'spura13' },
      },
    ],
  },
  spura9: {
    brand: null,
    title: '얼마 남나?',
    sub: '월 순이익 약 220만 (15평·직원1명)',
    breadcrumb: ['푸라닭', '얼마 남나?'],
    cards: [
      {
        title: '재료비',
        hint: '매출의 고정 비율',
        val: '-380만원',
        valColor: 'red',
        row1Val: '매출의 38% 고정',
        row1Label: '본사 공급 80% · 절감 여지 소폭',
        tags: [
          { label: '절감 여지 제한적', type: 'warn' },
          { label: '허브재료 단가 높음', type: 'warn' },
        ],
        text: '허브 재료 특성상 일반 치킨보다 원재료 단가 높음. 본사 공급 외 일부 직접 구매 가능.',
        qBtn: { label: '허브재료 비싸면 원가가 더 높아? →', target: 'spura13' },
      },
      {
        title: '인건비',
        hint: '직원 1명 기준',
        val: '-200만원',
        valColor: 'yellow',
        row1Val: '200만원 기본',
        row1Label: '소규모 매장 · 파트타임 활용 가능',
        tags: [
          { label: '소규모 운영 유리', type: 'ok' },
          { label: '매년 상승', type: 'warn' },
        ],
        text: '소규모 매장 특성상 파트타임 활용이 쉬워 인건비 조절 여지 있음.',
        qBtn: { label: '파트타임으로 운영하면 품질 유지돼? →', target: 'spura1' },
      },
      {
        title: '임대료',
        hint: '15평 평균',
        val: '-120만원',
        valColor: 'green',
        row1Val: '평균 120만원',
        row1Label: '소규모 매장 · 임대료 부담 낮음',
        tags: [
          { label: '소규모 상권 가능', type: 'ok' },
          { label: '권리금 별도', type: 'warn' },
        ],
        text: '15평 소규모 매장으로 임대료 부담 낮은 것이 최대 장점. 주택가 상권도 가능.',
        qBtn: { label: '주택가에서도 장사가 돼? →', target: 'spura1' },
      },
      {
        title: '실제 순이익',
        hint: '모든 비용 제외 후',
        val: '약 220만원',
        valColor: 'yellow',
        row1Val: '약 220만원',
        row1Label: '매출 1,000만 · 직원 1명 기준',
        tags: [
          { label: '직원 2명 → 50만대', type: 'warn' },
          { label: '매출 1,300만 → 350만', type: 'neu' },
        ],
        text: '절대 금액은 낮지만 투자금 대비 회수 기간은 3대 브랜드보다 짧을 수 있음.',
        qBtn: { label: '월 220인데 투자금 회수에 몇 년 걸려? →', target: 'spura5' },
      },
    ],
  },
  spura13: {
    brand: null,
    title: '어디서 망하나?',
    sub: '오픈 6개월이 가장 위험한 구간',
    breadcrumb: ['푸라닭', '어디서 망하나?'],
    cards: [
      {
        title: '집객 부족',
        hint: '폐업 원인 1위',
        val: '40%',
        valColor: 'red',
        row1Val: '폐업의 40%',
        row1Label: '브랜드 파워 부재로 직격탄',
        tags: [
          { label: 'SNS 마케팅 필수', type: 'warn' },
          { label: '배달앱 광고비 부담', type: 'warn' },
        ],
        text: '브랜드 자체 집객이 없어 오픈 후 본인이 직접 손님을 만들어야 함. 마케팅 비용 추가 발생.',
        qBtn: { label: '마케팅 안 하면 얼마나 빨리 망해? →', target: 'spura9' },
      },
      {
        title: '입지 실패',
        hint: '폐업 원인 2위',
        val: '30%',
        valColor: 'red',
        row1Val: '폐업의 30%',
        row1Label: '유동인구 없는 상권 오픈',
        tags: [
          { label: '배달 상권 필수', type: 'warn' },
          { label: '조사 최소 3회', type: 'warn' },
        ],
        text: '브랜드 파워 없으니 입지가 더 중요. 배달 수요 높은 상권 선정이 생존 핵심.',
        qBtn: { label: '오픈하고 나면 입지는 못 바꾼다고? →', target: 'spura1' },
      },
      {
        title: '자금 소진',
        hint: '초기 운영 위기',
        val: '20%',
        valColor: 'yellow',
        row1Val: '오픈 3~4개월차 위험',
        row1Label: '집객 안 되면 예비금 빠르게 소진',
        tags: [
          { label: '예비금 2천 필수', type: 'warn' },
          { label: '마케팅비 예산 확보', type: 'warn' },
        ],
        text: '초기 투자비는 낮지만 집객이 안 되면 예비금 소진 속도가 빠름.',
        qBtn: { label: '예비금 없으면 언제 망해? →', target: 'spura5' },
      },
      {
        title: '번아웃 폐업',
        hint: '체력·정신 소모',
        val: '10%',
        valColor: 'yellow',
        row1Val: '폐업의 10%',
        row1Label: '마케팅+운영 이중 부담',
        tags: [
          { label: '마케팅 직접 해야 함', type: 'warn' },
          { label: '운영+홍보 이중 소모', type: 'warn' },
        ],
        text: '조리는 단순하나 SNS·배달앱 관리까지 혼자 하면 정신적 소모 큼.',
        qBtn: { label: '월 220 벌려고 이 고생을 해야 해? →', target: 'spura9' },
      },
    ],
  },
}
