import autoKyochonNews from './auto-kyochon-news.json'

const autoKyochonInsight = autoKyochonNews?.displayLine || '1위 브랜드, 간판이 손님 데려와요.'

export const screens = {
  s0: {
    brand: null,
    title: '어느 브랜드가 궁금해?',
    sub: '브랜드를 선택하면 핵심만 빠르게 파고듭니다',
    breadcrumb: null,
    cards: [
      {
        title: '교촌치킨',
        hint: '업계 1위 · 간장치킨 강자',
        val: '업계 1위',
        valColor: 'green',
        row1Val: '가맹점 수 1,361개',
        row1Label: '업계 최다 · 간장·허니 시리즈 강세',
        tags: [
          { label: '브랜드 1위', type: 'ok' },
          { label: '가맹비 높음', type: 'warn' },
          { label: '자금 2억+', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: autoKyochonInsight },
          { dot: 'gold', text: '2억 넘게 써야 시작할 수 있어요.' },
        ],
        qBtn: { label: '브랜드 최강인데 왜 2억을 써야 해?', target: 'sgyo0' },
      },
      {
        title: '비비큐(BBQ)',
        hint: '업계 2위 · 황금올리브치킨',
        val: '업계 2위',
        valColor: 'green',
        row1Val: '가맹점 수 2,316개',
        row1Label: '해외 진출 · 프리미엄 포지셔닝',
        tags: [
          { label: '브랜드 2위', type: 'ok' },
          { label: '가격 프리미엄', type: 'neu' },
          { label: '광고비 별도', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '50개국 나간 이름, 손님이 알아서 와요.' },
          { dot: 'gold', text: '마리 2만 원대, 잘 팔리지만 눈치 봐요.' },
        ],
        qBtn: { label: '비싼 치킨, 불황 오면 첫 번째로 망한다고?', target: 'sbbq0' },
      },
      {
        title: 'BHC치킨',
        hint: '업계 3위 · 뿌링클 강세',
        val: '업계 3위',
        valColor: 'yellow',
        row1Val: '가맹점 수 2,228개',
        row1Label: '뿌링클·맛초킹 · 배달 강세',
        tags: [
          { label: '브랜드 3위', type: 'neu' },
          { label: '자금 1.5억+', type: 'warn' },
          { label: '초보 가능', type: 'ok' },
        ],
        insights: [
          { dot: 'teal', text: '매뉴얼 잘 돼있어 처음도 할 수 있어요.' },
          { dot: 'gold', text: '1.5억 써야 해요. 3개월이 고비예요.' },
        ],
        qBtn: { label: '초보도 된다는데, 1.5억 쓰고 월 280이 전부야?', target: 'sbhc0' },
      },
      {
        title: '푸라닭치킨',
        hint: '중견 브랜드 · 허브치킨',
        val: '소자본 가능',
        valColor: 'green',
        row1Val: '가맹점 수 715개',
        row1Label: '허브시리즈 · 소규모 매장 가능',
        tags: [
          { label: '초기비용 낮음', type: 'ok' },
          { label: '브랜드 인지도↓', type: 'warn' },
          { label: '소자본 창업', type: 'ok' },
        ],
        insights: [
          { dot: 'teal', text: '1억 미만으로 시작할 수 있어요.' },
          { dot: 'gold', text: '이미지는 뚜렷해요. 하지만 손님을 계속 불러오는 힘은 따로 봐야 해요.', source: '베이비뉴스' },
        ],
        qBtn: { label: '1억으로 치킨집, 진짜 될까?', target: 'spura0' },
      },
    ],
  },
  sbhc0: {
    brand: 'BHC 치킨',
    title: '뭐가 궁금해?',
    sub: '핵심만 빠르게 파고드세요',
    breadcrumb: null,
    cards: [
      {
        title: '해볼 만할까?',
        brandKey: 'BHC치킨',
        hint: '솔직한 한 줄 평가',
        val: '중상',
        valColor: 'yellow',
        row1Val: '종합 평가: 중상',
        row1Label: '초보 진입 가능 · 브랜드 3위 · 자금 부담 큼',
        tags: [
          { label: '초보자 가능', type: 'ok' },
          { label: '자금 1.5억+', type: 'warn' },
          { label: '브랜드 3위', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '브랜드는 계속 새 이야기를 만듭니다. 점주는 그 이야기가 매출로 이어지는지 봐야 해요.', source: 'KFE뉴스' },
          { dot: 'gold', text: '2억 못 채우면 3개월이 고비예요.' },
        ],
        qBtn: { label: '3개월 안에 위기 온다는데, 진짜야? →', target: 's1' },
      },
      {
        title: '얼마 드나?',
        brandKey: 'BHC치킨',
        hint: '초기 투자 현실적으로',
        val: '1억 5천',
        valColor: 'red',
        row1Val: '총 1억 5,000만원',
        row1Label: '보증금 포함 시 최대 2억',
        tags: [
          { label: '가맹비 900만', type: 'warn' },
          { label: '인테리어 6.5천', type: 'warn' },
          { label: '예비금 별도', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '총 1.5억, 공개된 금액이에요.' },
          { dot: 'gold', text: '보증금·예비금 더하면 2억 돼요.' },
        ],
        qBtn: { label: '1억 5천인데 왜 2억이 필요하다고? →', target: 's5' },
      },
      {
        title: '얼마 남나?',
        brandKey: 'BHC치킨',
        hint: '한 달 실제 순이익',
        val: '약 280만',
        valColor: 'yellow',
        row1Val: '월 순이익 280만원',
        row1Label: '매출 1,200만 · 직원 1명 기준',
        tags: [
          { label: '재료비 -456만', type: 'warn' },
          { label: '인건비 -250만', type: 'warn' },
          { label: '임대료 -150만', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '잘 되면 한 달에 280만 남아요.' },
          { dot: 'gold', text: '직원 한 명 더 쓰면 100만대예요.' },
        ],
        qBtn: { label: '열심히 해도 월 280이 전부야? →', target: 's9' },
      },
      {
        title: '어디서 망하나?',
        brandKey: 'BHC치킨',
        hint: '폐업 패턴 분석',
        val: '입지 1위',
        valColor: 'red',
        row1Val: '입지 실패 38%',
        row1Label: '오픈 후 3~6개월이 최대 위험',
        tags: [
          { label: '입지 38%', type: 'warn' },
          { label: '자금 31%', type: 'warn' },
          { label: '본사갈등 18%', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '망하는 이유 1위는 자리예요.' },
          { dot: 'gold', text: '오픈 3~6개월이 가장 위험해요.' },
        ],
        qBtn: { label: '10명 중 3명이 망한다고? →', target: 's13' },
      },
    ],
  },
  s1: {
    brand: null,
    title: '해볼 만할까?',
    sub: '4가지 핵심으로 파악',
    breadcrumb: ['BHC', '해볼 만할까?'],
    cards: [
      {
        title: '브랜드 파워',
        hint: '치킨 시장 인지도',
        val: '상위 3위',
        valColor: 'green',
        row1Val: '인지도 98%',
        row1Label: '재방문율 62% · 배달앱 상위 5%',
        tags: [
          { label: '자연 집객 가능', type: 'ok' },
          { label: '로열티 2~3%', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '이름은 잘 알려져 있어요. 알려진 만큼 비교도 많이 당해요.', source: '뉴데일리' },
          { dot: 'gold', text: '로열티가 매달 2~3% 빠져나가요.' },
        ],
        qBtn: { label: '브랜드 좋은데 왜 30%가 망해? →', target: 's13' },
      },
      {
        title: '초보자 난이도',
        hint: '시스템화 수준',
        val: '낮음',
        valColor: 'green',
        row1Val: '교육 3주 후 운영',
        row1Label: '매뉴얼 완성도 상',
        tags: [
          { label: '레시피 표준화', type: 'ok' },
          { label: '1인 운영 불가', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '3주 교육 받으면 혼자 돌려요.' },
          { dot: 'gold', text: '가맹 이야기는 숫자로 봐야 해요. 말보다 계약서와 비용표가 중요해요.', source: '신아일보' },
        ],
        qBtn: { label: '쉽다더니 왜 혼자는 못 하나? →', target: 's9' },
      },
      {
        title: '경쟁 강도',
        hint: '주변 밀집도',
        val: '높음',
        valColor: 'red',
        row1Val: '반경 500m 내 4.2개',
        row1Label: '치킨집 전국 8.7만개',
        tags: [
          { label: '동일브랜드 500m 보호', type: 'ok' },
          { label: '타브랜드 무제한', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '같은 BHC는 500m 안에 못 열어요.' },
          { dot: 'gold', text: '논란은 지나갈 수 있어요. 하지만 브랜드 신뢰는 한 번 흔들리면 오래 가요.', source: '미디어펜' },
        ],
        qBtn: { label: '치킨집이 편의점보다 많다고? →', target: 's13' },
      },
      {
        title: '폐업 위험도',
        hint: '업계 통계 기반',
        val: '주의 필요',
        valColor: 'red',
        row1Val: '3년 내 폐업률 30%',
        row1Label: '오픈 6개월이 최대 위험',
        tags: [
          { label: '입지 실패 1위', type: 'warn' },
          { label: '자금 소진 2위', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '분쟁 신호가 보여요. 장사보다 계약이 먼저 발목 잡을 수 있어요.', source: '뉴스웍스' },
          { dot: 'gold', text: '3년 안에 10명 중 3명 문 닫아요.' },
        ],
        qBtn: { label: '어디서 가장 많이 걸려서 망하나? →', target: 's13' },
      },
    ],
  },
  s5: {
    brand: null,
    title: '얼마 드나?',
    sub: '총 1억 5천 ~ 최대 2억',
    breadcrumb: ['BHC', '얼마 드나?'],
    cards: [
      {
        title: '가맹비',
        hint: '계약 시 일시납',
        official: true,
        val: '770만원',
        valColor: 'yellow',
        row1Val: '770만원 일시납 (딜리버리 기준)',
        row1Label: '2년 계약 · 1년 단위 갱신',
        tags: [
          { label: '비어존은 1,100만', type: 'neu' },
          { label: '환불 조건 까다로움', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '딜리버리 770만, 비어존 1,100만 원이에요.' },
          { dot: 'gold', text: '가맹 이야기는 숫자로 봐야 해요. 말보다 계약서와 비용표가 중요해요.', source: '비즈트리뷴' },
        ],
        qBtn: { label: '계약 취소하면 돈 돌려받을 수 있어? →', target: 's13' },
      },
      {
        title: '인테리어',
        hint: '본사 지정업체 강제',
        val: '4,620만원',
        valColor: 'red',
        row1Val: '4,620만원 (비어존 66㎡)',
        row1Label: '딜리버리 전용 33㎡는 1,760만 · 5년마다 리모델링',
        tags: [
          { label: '딜리버리 1,760만', type: 'neu' },
          { label: '직접 업체 불가', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '홀+배달 비어존 66㎡ 기준 4,620만 원이에요.' },
          { dot: 'gold', text: '배달전용 딜리버리는 1,760만으로 훨씬 싸요.' },
        ],
        qBtn: { label: '인테리어에 본사 마진이 포함됐다고? →', target: 's13' },
      },
      {
        title: '장비/설비',
        hint: '주방 장비 일체',
        val: '4,800만원',
        valColor: 'red',
        row1Val: '4,800만원',
        row1Label: '튀김기·냉장·POS 포함',
        tags: [
          { label: '튀김기 3년 교체', type: 'warn' },
          { label: 'POS 300만', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '튀김기·냉장·POS 포함 4,800만이에요.' },
          { dot: 'gold', text: '튀김기는 3년 되면 또 사야 해요.' },
        ],
        qBtn: { label: '3년마다 또 수천만이 나간다고? →', target: 's9' },
      },
      {
        title: '숨겨진 비용',
        hint: '보증금 + 예비금',
        val: '+3천만 이상',
        valColor: 'red',
        row1Val: '보증금 1,000만 + 예비금 별도',
        row1Label: '임대비·초도상품비 공개 금액 외 별도',
        tags: [
          { label: '보증금 1,000만 (공식)', type: 'warn' },
          { label: '예비금 2,000만+', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '보증금 1,000만은 계약 종료 시 돌려받아요.' },
          { dot: 'gold', text: '가격은 묶였어요. 대신 비용 부담은 어딘가에 남아요.', source: '대일경제' },
        ],
        qBtn: { label: '돈 모자라면 정확히 어느 순간 망해? →', target: 's13' },
      },
    ],
  },
  s9: {
    brand: null,
    title: '얼마 남나?',
    sub: '월 순이익 약 280만 (20평·직원1명)',
    breadcrumb: ['BHC', '얼마 남나?'],
    cards: [
      {
        title: '재료비',
        hint: '매출의 고정 비율',
        val: '-47.6%',
        valColor: 'red',
        row1Val: '딜리버리 47.6% · 비어존 43.5%',
        row1Label: '본사 공급 99% (딜리버리) · 절감 불가',
        tags: [
          { label: '본사 공급 99%', type: 'warn' },
          { label: '절감 여지 없음', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '딜리버리는 매출의 47.6%, 줄일 방법이 없어요.' },
          { dot: 'gold', text: '본사에서 99% 강제 구매라 단가 통제 불가예요.' },
        ],
        qBtn: { label: '본사가 단가 올리면 내가 다 떠안아? →', target: 's13' },
      },
      {
        title: '인건비',
        hint: '직원 1명 기준',
        val: '-250만원',
        valColor: 'red',
        row1Val: '250만원 기본',
        row1Label: '주말 알바 +80만 추가 가능',
        tags: [
          { label: '1인 운영 불가', type: 'warn' },
          { label: '매년 상승', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '직원 1명 기준 250만 원이에요.' },
          { dot: 'gold', text: '가격 얘기가 나왔어요. 손님도 점주도 계산기를 두드리는 구간이에요.', source: '뉴스TNT' },
        ],
        qBtn: { label: '혼자 다 하면 1~2년 안에 번아웃 온다고? →', target: 's13' },
      },
      {
        title: '임대료',
        hint: '20평 평균',
        val: '-150만원',
        valColor: 'yellow',
        row1Val: '평균 150만원',
        row1Label: '상권에 따라 50~500만 차이',
        tags: [
          { label: '200만 되면 반토막', type: 'warn' },
          { label: '권리금 별도', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '월 1,050만 매출이 손익 기준이에요.' },
          { dot: 'gold', text: '임대료 50만 차이가 순이익 반 날려요.' },
        ],
        qBtn: { label: '임대 50만 차이가 순이익을 반으로 만든다고? →', target: 's13' },
      },
      {
        title: '실제 순이익',
        hint: '모든 비용 제외 후',
        val: '약 280만원',
        valColor: 'yellow',
        row1Val: '약 280만원',
        row1Label: '매출 1,200만 · 직원 1명 기준',
        tags: [
          { label: '직원 2명 → 100만대', type: 'warn' },
          { label: '매출 1,500만 → 420만', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '매출 200만 올리면 순이익 50% 올라요.' },
          { dot: 'gold', text: '할인은 손님을 부릅니다. 대신 남는 돈도 같이 깎일 수 있어요.', source: '이코노뉴스' },
        ],
        qBtn: { label: '직원 한 명 더 쓰면 남는 게 없다고? →', target: 's13' },
      },
    ],
  },
  s13: {
    brand: null,
    title: '어디서 망하나?',
    sub: '오픈 6개월이 가장 위험한 구간',
    breadcrumb: ['BHC', '어디서 망하나?'],
    cards: [
      {
        title: '입지 실패',
        hint: '폐업 원인 1위',
        val: '38%',
        valColor: 'red',
        row1Val: '폐업의 38%',
        row1Label: '사전 조사가 생존을 결정',
        tags: [
          { label: '배달vs홀 미스매치', type: 'warn' },
          { label: '조사 최소 3회', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '망하는 이유 1위, 자리 잘못 잡은 거예요.' },
          { dot: 'gold', text: '분쟁 신호가 보여요. 장사보다 계약이 먼저 발목 잡을 수 있어요.', source: 'KFE뉴스' },
        ],
        qBtn: { label: '오픈하고 나면 입지는 못 바꾼다고? →', target: 's1' },
      },
      {
        title: '자금 소진',
        hint: '초기 운영 위기',
        val: '31%',
        valColor: 'red',
        row1Val: '오픈 3개월차 최대 위험',
        row1Label: '오픈 버프 끝나는 시점',
        tags: [
          { label: '예비금 3천 필수', type: 'warn' },
          { label: '대출이자 포함 계획', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '오픈 1~2개월은 손님이 몰려요.' },
          { dot: 'gold', text: '3~4개월차에 돈이 제일 많이 나가요.' },
        ],
        qBtn: { label: '3개월 버티는 데 돈이 얼마나 필요해? →', target: 's5' },
      },
      {
        title: '본사 갈등',
        hint: '계약 분쟁',
        val: '18%',
        valColor: 'yellow',
        row1Val: '위약금 = 월매출 10% × 잔여개월',
        row1Label: '공정위 시정조치 2건 (2023~2024)',
        tags: [
          { label: '위약벌 전월매출 20%', type: 'warn' },
          { label: '공정위 제재 2건', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '월매출 4,400만 · 잔여 12개월이면 위약금 5,280만이에요.' },
          { dot: 'gold', text: '외부 재료 쓰면 전월매출 20% 위약벌이 붙어요.' },
        ],
        qBtn: { label: '그만두고 싶어도 못 나온다고? →', target: 's5' },
      },
      {
        title: '번아웃 폐업',
        hint: '체력·정신 소모',
        val: '13%',
        valColor: 'yellow',
        row1Val: '폐업의 13%',
        row1Label: '주 7일 장시간 노동',
        tags: [
          { label: '1인 운영 시 고위험', type: 'warn' },
          { label: '1~2년 내 한계', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '치킨은 주 7일, 하루 12시간이에요.' },
          { dot: 'gold', text: '1~2년차에 체력 한계 오는 경우 많아요.' },
        ],
        qBtn: { label: '월 280 벌려고 주 7일 일하는 거 맞아? →', target: 's9' },
      },
    ],
  },
  sgyo0: {
    brand: '교촌치킨',
    title: '뭐가 궁금해?',
    sub: '핵심만 빠르게 파고드세요',
    breadcrumb: null,
    cards: [
      {
        title: '해볼 만할까?',
        brandKey: '교촌치킨',
        hint: '솔직한 한 줄 평가',
        val: '중상',
        valColor: 'yellow',
        row1Val: '종합 평가: 중상',
        row1Label: '브랜드 1위 · 초기비용 최고 · 본사 통제 강함',
        tags: [
          { label: '브랜드 1위', type: 'ok' },
          { label: '자금 2억+', type: 'warn' },
          { label: '본사 통제 강함', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '업계 1위, 이름 하나는 최강이에요.' },
          { dot: 'gold', text: '2억 넘게 쓰고 본사 규정도 빡빡해요.' },
        ],
        qBtn: { label: '브랜드 1위인데 왜 통제가 강하다고? →', target: 'sgyo1' },
      },
      {
        title: '얼마 드나?',
        brandKey: '교촌치킨',
        hint: '초기 투자 현실적으로',
        val: '1억 3천',
        valColor: 'red',
        row1Val: '총 1억~1억 3천만원',
        row1Label: '임대비·권리금 제외 추정액',
        tags: [
          { label: '가맹비 660만', type: 'warn' },
          { label: '인테리어 5.9천+', type: 'warn' },
          { label: '예비금 별도', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '총 1억~1.3억, BBQ보다 저렴해요.' },
          { dot: 'gold', text: '가맹 이야기는 숫자로 봐야 해요. 말보다 계약서와 비용표가 중요해요.', source: '포인트데일리' },
        ],
        qBtn: { label: '교촌 창업 비용이 진짜 얼마야? →', target: 'sgyo5' },
      },
      {
        title: '얼마 남나?',
        brandKey: '교촌치킨',
        hint: '한 달 실제 순이익',
        val: '약 500만',
        valColor: 'yellow',
        row1Val: '월 순이익 약 500만원',
        row1Label: '연 평균매출 7.3억 기준 추정',
        tags: [
          { label: '재료비 45~50%', type: 'warn' },
          { label: '인건비 15~20%', type: 'warn' },
          { label: '임대료 5~10%', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '잘 되면 한 달에 400~600만 남아요.' },
          { dot: 'gold', text: '가격은 묶였어요. 대신 비용 부담은 어딘가에 남아요.', source: '스포츠한국' },
        ],
        qBtn: { label: '평균 7.3억 팔아도 순이익이 500만뿐이야? →', target: 'sgyo9' },
      },
      {
        title: '어디서 망하나?',
        brandKey: '교촌치킨',
        hint: '폐업 패턴 분석',
        val: '자금 1위',
        valColor: 'red',
        row1Val: '자금 소진 35%',
        row1Label: '높은 초기비용이 가장 큰 리스크',
        tags: [
          { label: '자금 35%', type: 'warn' },
          { label: '입지 33%', type: 'warn' },
          { label: '본사갈등 20%', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '자금 소진이 망하는 이유 1위예요.' },
          { dot: 'gold', text: '2억 쓰고 손익분기 전에 바닥나요.' },
        ],
        qBtn: { label: '2억 넘게 쓰고 망하면 얼마나 날아가? →', target: 'sgyo13' },
      },
    ],
  },
  sgyo1: {
    brand: null,
    title: '해볼 만할까?',
    sub: '4가지 핵심으로 파악',
    breadcrumb: ['교촌', '해볼 만할까?'],
    cards: [
      {
        title: '브랜드 파워',
        hint: '치킨 시장 인지도',
        val: '업계 1위',
        valColor: 'green',
        row1Val: '인지도 99%',
        row1Label: '재방문율 68% · 배달앱 상위 3%',
        tags: [
          { label: '자연 집객 최강', type: 'ok' },
          { label: '로열티 2%', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '브랜드는 계속 새 이야기를 만듭니다. 점주는 그 이야기가 매출로 이어지는지 봐야 해요.', source: '비즈니스포스트' },
          { dot: 'gold', text: '로열티가 매달 2% 빠져나가요.' },
        ],
        qBtn: { label: '브랜드 최강인데 왜 비용도 최강이야? →', target: 'sgyo5' },
      },
      {
        title: '초보자 난이도',
        hint: '시스템화 수준',
        val: '보통',
        valColor: 'yellow',
        row1Val: '교육 4주 후 운영',
        row1Label: '메뉴 복잡도 높음',
        tags: [
          { label: '레시피 표준화', type: 'ok' },
          { label: '메뉴 수 많음', type: 'warn' },
          { label: '1인 운영 불가', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '4주 교육 받으면 혼자 돌려요.' },
          { dot: 'gold', text: '이미지는 좋아져요. 그래도 점주에게 중요한 건 결국 하루 매출이에요.', source: '뉴스퀘스트' },
        ],
        qBtn: { label: '메뉴 많으면 운영이 얼마나 힘들어? →', target: 'sgyo9' },
      },
      {
        title: '경쟁 강도',
        hint: '주변 밀집도',
        val: '높음',
        valColor: 'red',
        row1Val: '반경 500m 내 4.8개',
        row1Label: '치킨집 전국 8.7만개',
        tags: [
          { label: '동일브랜드 500m 보호', type: 'ok' },
          { label: '타브랜드 무제한', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '같은 교촌은 500m 안에 못 열어요.' },
          { dot: 'gold', text: '가격 얘기가 나왔어요. 손님도 점주도 계산기를 두드리는 구간이에요.', source: '서울와이어' },
        ],
        qBtn: { label: '보호구역 있어도 경쟁 심하다고? →', target: 'sgyo13' },
      },
      {
        title: '폐업 위험도',
        hint: '업계 통계 기반',
        val: '주의 필요',
        valColor: 'red',
        row1Val: '3년 내 폐업률 28%',
        row1Label: '오픈 6개월이 최대 위험',
        tags: [
          { label: '자금 소진 1위', type: 'warn' },
          { label: '입지 실패 2위', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '분쟁 신호가 보여요. 장사보다 계약이 먼저 발목 잡을 수 있어요.', source: '서울타임스' },
          { dot: 'gold', text: '3년 안에 10명 중 3명 문 닫아요.' },
        ],
        qBtn: { label: '어디서 가장 많이 걸려서 망하나? →', target: 'sgyo13' },
      },
    ],
  },
  sgyo5: {
    brand: null,
    title: '얼마 드나?',
    sub: '총 1억 ~ 최대 1억 3천',
    breadcrumb: ['교촌', '얼마 드나?'],
    cards: [
      {
        title: '가맹비',
        hint: '계약 시 일시납',
        val: '660만원',
        valColor: 'yellow',
        row1Val: '660만원 일시납 (표준형, VAT 포함)',
        row1Label: '3년 계약 · 1년 단위 갱신',
        tags: [
          { label: '배달전용형은 330만', type: 'neu' },
          { label: '환불 조건 까다로움', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '660만 원, 교육비 355만 별도예요.' },
          { dot: 'gold', text: '1개월 지나면 못 돌려받아요.' },
        ],
        qBtn: { label: '교육비가 왜 따로 있어? →', target: 'sgyo13' },
      },
      {
        title: '인테리어',
        hint: '가맹점 직접 시공업체 계약',
        val: '5,888만원~',
        valColor: 'red',
        row1Val: '66㎡ 기준 5,888~6,900만원',
        row1Label: '3.3㎡당 294~345만원',
        tags: [
          { label: '배달형(33㎡) 3,597만~', type: 'neu' },
          { label: '도서지역 35% 추가', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '66㎡(약 20평) 기준 최소 5,888만 원이에요.' },
          { dot: 'gold', text: '논란은 지나갈 수 있어요. 하지만 브랜드 신뢰는 한 번 흔들리면 오래 가요.', source: '뉴스워커' },
        ],
        qBtn: { label: '인테리어 비용이 왜 이렇게 달라? →', target: 'sgyo13' },
      },
      {
        title: '장비/설비',
        hint: '주방 장비 일체',
        val: '933만원',
        valColor: 'yellow',
        row1Val: '933만원 (냉장·냉동 별도 1,370만+)',
        row1Label: '튀김기 397만 + 주방용품 536만',
        tags: [
          { label: '냉장·냉동·온수기 별도', type: 'warn' },
          { label: '총 기기 약 2,300만+', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '튀김기+주방용품 933만원이에요 (냉장·냉동 별도).' },
          { dot: 'gold', text: '냉장고·냉동고 등 평균 1,370만 추가로 필요해요.' },
        ],
        qBtn: { label: '냉장고도 따로 사야 해? →', target: 'sgyo9' },
      },
      {
        title: '숨겨진 비용',
        hint: '보증금 + 예비금',
        val: '+3천만+',
        valColor: 'red',
        row1Val: '보증금 1,000만 + 예비금 별도',
        row1Label: '임대보증금·권리금·초도상품비 별도',
        tags: [
          { label: '보증금 1,000만 (공식)', type: 'warn' },
          { label: '예비금 2,000만+', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '보증금 1,000만은 계약 종료 시 돌려받아요.' },
          { dot: 'gold', text: '가격은 묶였어요. 대신 비용 부담은 어딘가에 남아요.', source: '스포츠한국' },
        ],
        qBtn: { label: '돈 모자라면 정확히 어느 순간 망해? →', target: 'sgyo13' },
      },
    ],
  },
  sgyo9: {
    brand: null,
    title: '얼마 남나?',
    sub: '월 순이익 약 400~600만 (연 평균매출 기준)',
    breadcrumb: ['교촌', '얼마 남나?'],
    cards: [
      {
        title: '재료비',
        hint: '매출의 고정 비율',
        val: '-520만원',
        valColor: 'red',
        row1Val: '매출의 40% 고정',
        row1Label: '본사 공급 90% · 절감 불가',
        tags: [
          { label: '절감 여지 없음', type: 'warn' },
          { label: '매출 줄어도 고정', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '매출의 40%, 본사에서 90% 사야 해요.' },
          { dot: 'gold', text: '대표 맛은 강해요. 대신 가격과 원가 이슈도 같이 따라옵니다.', source: '로이슈' },
        ],
        qBtn: { label: '본사 공급 90%면 내 마음대로 못 해? →', target: 'sgyo13' },
      },
      {
        title: '인건비',
        hint: '직원 1명 기준',
        val: '-250만원',
        valColor: 'red',
        row1Val: '250만원 기본',
        row1Label: '주말 알바 +80만 추가 가능',
        tags: [
          { label: '1인 운영 불가', type: 'warn' },
          { label: '매년 상승', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '직원 1명 기준 250만 원이에요.' },
          { dot: 'gold', text: '가맹 이야기는 숫자로 봐야 해요. 말보다 계약서와 비용표가 중요해요.', source: '포인트데일리' },
        ],
        qBtn: { label: '메뉴 복잡해서 알바 구하기 어렵다고? →', target: 'sgyo13' },
      },
      {
        title: '임대료',
        hint: '20평 평균',
        val: '-150만원',
        valColor: 'yellow',
        row1Val: '평균 150만원',
        row1Label: '상권에 따라 50~500만 차이',
        tags: [
          { label: '200만 되면 반토막', type: 'warn' },
          { label: '권리금 별도', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '이미지는 좋아져요. 그래도 점주에게 중요한 건 결국 하루 매출이에요.', source: '뉴스퀘스트' },
          { dot: 'gold', text: '할인은 손님을 부릅니다. 대신 남는 돈도 같이 깎일 수 있어요.', source: '경향뉴스' },
        ],
        qBtn: { label: '좋은 상권 들어가면 임대료가 얼마야? →', target: 'sgyo13' },
      },
      {
        title: '실제 순이익',
        hint: '모든 비용 제외 후',
        val: '약 500만원',
        valColor: 'yellow',
        row1Val: '약 400~600만원',
        row1Label: '연 평균매출 7.3억 기준 추정',
        tags: [
          { label: '순이익률 7~10%', type: 'neu' },
          { label: '매출 규모 따라 편차 큼', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '평균 가맹점 기준 월 400~600만 남아요.' },
          { dot: 'gold', text: '브랜드는 계속 새 이야기를 만듭니다. 점주는 그 이야기가 매출로 이어지는지 봐야 해요.', source: '비즈니스포스트' },
        ],
        qBtn: { label: '월 500이면 투자금 회수에 몇 년 걸려? →', target: 'sgyo5' },
      },
    ],
  },
  sgyo13: {
    brand: null,
    title: '어디서 망하나?',
    sub: '오픈 6개월이 가장 위험한 구간',
    breadcrumb: ['교촌', '어디서 망하나?'],
    cards: [
      {
        title: '자금 소진',
        hint: '폐업 원인 1위',
        val: '35%',
        valColor: 'red',
        row1Val: '폐업의 35%',
        row1Label: '높은 초기비용이 직격탄',
        tags: [
          { label: '예비금 3천 필수', type: 'warn' },
          { label: '손익분기 5~7개월', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '망하는 이유 1위, 돈 먼저 바닥나요.' },
          { dot: 'gold', text: '2억 쓰고 손익분기에 5~7개월 걸려요.' },
        ],
        qBtn: { label: '손익분기까지 버티는 게 왜 이렇게 힘들어? →', target: 'sgyo5' },
      },
      {
        title: '입지 실패',
        hint: '폐업 원인 2위',
        val: '33%',
        valColor: 'red',
        row1Val: '폐업의 33%',
        row1Label: '사전 조사가 생존을 결정',
        tags: [
          { label: '배달vs홀 미스매치', type: 'warn' },
          { label: '조사 최소 3회', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '이미지는 좋아져요. 그래도 점주에게 중요한 건 결국 하루 매출이에요.', source: '뉴스퀘스트' },
          { dot: 'gold', text: '분쟁 신호가 보여요. 장사보다 계약이 먼저 발목 잡을 수 있어요.', source: '서울타임스' },
        ],
        qBtn: { label: '오픈하고 나면 입지는 못 바꾼다고? →', target: 'sgyo1' },
      },
      {
        title: '본사 갈등',
        hint: '계약 분쟁',
        val: '20%',
        valColor: 'yellow',
        row1Val: '폐업의 20%',
        row1Label: '계약서 안 보면 당함',
        tags: [
          { label: '단가 연 3~5% 강제 인상', type: 'warn' },
          { label: '메뉴 강제 변경', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '3사 중 본사 규정이 가장 빡빡해요.' },
          { dot: 'gold', text: '가맹 이야기는 숫자로 봐야 해요. 말보다 계약서와 비용표가 중요해요.', source: '포인트데일리' },
        ],
        qBtn: { label: '그만두고 싶어도 못 나온다고? →', target: 'sgyo5' },
      },
      {
        title: '번아웃 폐업',
        hint: '체력·정신 소모',
        val: '12%',
        valColor: 'yellow',
        row1Val: '폐업의 12%',
        row1Label: '주 7일 장시간 노동',
        tags: [
          { label: '1인 운영 시 고위험', type: 'warn' },
          { label: '1~2년 내 한계', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '논란은 지나갈 수 있어요. 하지만 브랜드 신뢰는 한 번 흔들리면 오래 가요.', source: '뉴스워커' },
          { dot: 'gold', text: '1~2년차에 체력 한계 오는 경우 많아요.' },
        ],
        qBtn: { label: '월 320 벌려고 주 7일 일하는 거 맞아? →', target: 'sgyo9' },
      },
    ],
  },
  sbbq0: {
    brand: '비비큐(BBQ)',
    title: '뭐가 궁금해?',
    sub: '핵심만 빠르게 파고드세요',
    breadcrumb: null,
    cards: [
      {
        title: '해볼 만할까?',
        brandKey: '비비큐(BBQ)',
        hint: '솔직한 한 줄 평가',
        val: '중상',
        valColor: 'yellow',
        row1Val: '종합 평가: 중상',
        row1Label: '브랜드 2위 · 프리미엄 전략 · 초기비용 높음',
        tags: [
          { label: '브랜드 2위', type: 'ok' },
          { label: '자금 2억+', type: 'warn' },
          { label: '객단가 높음', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '브랜드 힘은 있어요. 비싼 이미지를 버틸 상권인지가 문제예요.', source: '파이낸셜투데이' },
          { dot: 'gold', text: '가맹은 시작보다 유지가 중요해요. 처음 돈보다 매달 나가는 돈을 봐야 해요.', source: '한국외식신문' },
        ],
        qBtn: { label: '프리미엄인데 왜 로열티가 부담이야? →', target: 'sbbq1' },
      },
      {
        title: '얼마 드나?',
        brandKey: '비비큐(BBQ)',
        hint: '초기 투자 현실적으로',
        val: '7,575만원',
        valColor: 'yellow',
        row1Val: '총 7,575만원 (올리브치킨 15평)',
        row1Label: '임대비·전기·가스 별도',
        tags: [
          { label: '가맹비 1,100만', type: 'warn' },
          { label: '인테리어 3,135만', type: 'warn' },
          { label: '예비금 별도', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '올리브치킨 기준 총 7,575만이에요.' },
          { dot: 'gold', text: '타입별 편차 큼 — 빌리지는 4억7천만이에요.' },
        ],
        qBtn: { label: '타입마다 투자비가 이렇게 달라? →', target: 'sbbq5' },
      },
      {
        title: '얼마 남나?',
        brandKey: '비비큐(BBQ)',
        hint: '한 달 실제 순이익',
        val: '약 340만',
        valColor: 'yellow',
        row1Val: '월 순이익 340만원',
        row1Label: '매출 1,400만 · 직원 1명 기준',
        tags: [
          { label: '재료비 -532만', type: 'warn' },
          { label: '인건비 -250만', type: 'warn' },
          { label: '로열티 -42만', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '잘 되면 한 달에 340만 남아요.' },
          { dot: 'gold', text: '가격은 묶였어요. 대신 비용 부담은 어딘가에 남아요.', source: '위키트리' },
        ],
        qBtn: { label: '매출 1,400인데 순이익이 340뿐이야? →', target: 'sbbq9' },
      },
      {
        title: '어디서 망하나?',
        brandKey: '비비큐(BBQ)',
        hint: '폐업 패턴 분석',
        val: '가격저항 1위',
        valColor: 'red',
        row1Val: '가격저항 32%',
        row1Label: '프리미엄 가격에 소비자 이탈',
        tags: [
          { label: '가격저항 32%', type: 'warn' },
          { label: '입지 31%', type: 'warn' },
          { label: '자금소진 25%', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '가격 얘기가 나왔어요. 손님도 점주도 계산기를 두드리는 구간이에요.', source: '머니투데이' },
          { dot: 'gold', text: '이미지는 좋아져요. 그래도 점주에게 중요한 건 결국 하루 매출이에요.', source: '반론보도' },
        ],
        qBtn: { label: '비싼 치킨 안 팔리면 어떻게 돼? →', target: 'sbbq13' },
      },
    ],
  },
  spura0: {
    brand: '푸라닭치킨',
    title: '뭐가 궁금해?',
    sub: '핵심만 빠르게 파고드세요',
    breadcrumb: null,
    cards: [
      {
        title: '해볼 만할까?',
        brandKey: '푸라닭치킨',
        hint: '솔직한 한 줄 평가',
        val: '중',
        valColor: 'yellow',
        row1Val: '종합 평가: 중',
        row1Label: '소자본 가능 · 인지도 낮음 · 틈새 전략',
        tags: [
          { label: '초기비용 낮음', type: 'ok' },
          { label: '브랜드 인지도↓', type: 'warn' },
          { label: '틈새 포지션', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '1억 미만으로 시작할 수 있어요.' },
          { dot: 'gold', text: '이미지는 뚜렷해요. 하지만 손님을 계속 불러오는 힘은 따로 봐야 해요.', source: '베이비뉴스' },
        ],
        qBtn: { label: '인지도 낮으면 손님이 올까? →', target: 'spura1' },
      },
      {
        title: '얼마 드나?',
        brandKey: '푸라닭치킨',
        hint: '초기 투자 현실적으로',
        val: '1억 내외',
        valColor: 'yellow',
        row1Val: '총 9천~1억 2천만원',
        row1Label: '3대 브랜드 대비 40% 저렴',
        tags: [
          { label: '가맹비 500만', type: 'ok' },
          { label: '인테리어 5천~', type: 'neu' },
          { label: '예비금 별도', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '총 9천~1.2억, 3사보다 훨씬 싸요.' },
          { dot: 'gold', text: '가맹 이야기는 숫자로 봐야 해요. 말보다 계약서와 비용표가 중요해요.', source: '포인트데일리' },
        ],
        qBtn: { label: '싸게 시작하면 나중에 더 드는 거 아냐? →', target: 'spura5' },
      },
      {
        title: '얼마 남나?',
        brandKey: '푸라닭치킨',
        hint: '한 달 실제 순이익',
        val: '약 280만',
        valColor: 'yellow',
        row1Val: '월 순이익 약 280만원',
        row1Label: '연 평균매출 4.5억 기준 추정',
        tags: [
          { label: '재료비 45~50%', type: 'warn' },
          { label: '인건비 15~20%', type: 'warn' },
          { label: '임대료 5~10%', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '투자금 회수는 3사보다 빠를 수 있어요.' },
          { dot: 'gold', text: '이름은 잘 알려져 있어요. 알려진 만큼 비교도 많이 당해요.', source: '세계일보' },
        ],
        qBtn: { label: '월 280만이면 너무 적은 거 아냐? →', target: 'spura9' },
      },
      {
        title: '어디서 망하나?',
        brandKey: '푸라닭치킨',
        hint: '폐업 패턴 분석',
        val: '집객 1위',
        valColor: 'red',
        row1Val: '집객 부족 40%',
        row1Label: '브랜드 인지도 부족이 직격탄',
        tags: [
          { label: '집객부족 40%', type: 'warn' },
          { label: '입지 30%', type: 'warn' },
          { label: '자금소진 20%', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '손님 모으는 게 가장 큰 숙제예요.' },
          { dot: 'gold', text: '할인은 손님을 부릅니다. 대신 남는 돈도 같이 깎일 수 있어요.', source: '이뉴스투데이' },
        ],
        qBtn: { label: '브랜드 힘 없이 어떻게 손님을 모아? →', target: 'spura13' },
      },
    ],
  },
  sbbq1: {
    brand: null,
    title: '해볼 만할까?',
    sub: '4가지 핵심으로 파악',
    breadcrumb: ['BBQ', '해볼 만할까?'],
    cards: [
      {
        title: '브랜드 파워',
        hint: '치킨 시장 인지도',
        val: '업계 2위',
        valColor: 'green',
        row1Val: '인지도 97%',
        row1Label: '재방문율 60% · 해외 50개국 진출',
        tags: [
          { label: '프리미엄 이미지', type: 'ok' },
          { label: '로열티 2~3%', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '가격은 묶였어요. 대신 비용 부담은 어딘가에 남아요.', source: '일요서울' },
          { dot: 'gold', text: '로열티가 매달 2~3% 빠져나가요.' },
        ],
        qBtn: { label: '프리미엄 브랜드인데 왜 30%가 망해? →', target: 'sbbq13' },
      },
      {
        title: '초보자 난이도',
        hint: '시스템화 수준',
        val: '낮음',
        valColor: 'green',
        row1Val: '교육 3주 후 운영',
        row1Label: '매뉴얼 완성도 상',
        tags: [
          { label: '레시피 표준화', type: 'ok' },
          { label: '1인 운영 불가', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '3주 교육 받으면 혼자 돌려요.' },
          { dot: 'gold', text: '가맹 이야기는 숫자로 봐야 해요. 말보다 계약서와 비용표가 중요해요.', source: '한국청년일보' },
        ],
        qBtn: { label: '쉽다더니 왜 혼자는 못 하나? →', target: 'sbbq9' },
      },
      {
        title: '경쟁 강도',
        hint: '주변 밀집도',
        val: '높음',
        valColor: 'red',
        row1Val: '반경 500m 내 4.5개',
        row1Label: '치킨집 전국 8.7만개',
        tags: [
          { label: '동일브랜드 500m 보호', type: 'ok' },
          { label: '타브랜드 무제한', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '같은 BBQ는 500m 안에 못 열어요.' },
          { dot: 'gold', text: '브랜드 힘은 있어요. 비싼 이미지를 버틸 상권인지가 문제예요.', source: '아주경제' },
        ],
        qBtn: { label: '비싼데 옆에 싼 치킨집 생기면? →', target: 'sbbq13' },
      },
      {
        title: '폐업 위험도',
        hint: '업계 통계 기반',
        val: '주의 필요',
        valColor: 'red',
        row1Val: '3년 내 폐업률 29%',
        row1Label: '오픈 6개월이 최대 위험',
        tags: [
          { label: '가격저항 1위', type: 'warn' },
          { label: '자금 소진 2위', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '논란은 지나갈 수 있어요. 하지만 브랜드 신뢰는 한 번 흔들리면 오래 가요.', source: '매일경제' },
          { dot: 'gold', text: '3년 안에 10명 중 3명 문 닫아요.' },
        ],
        qBtn: { label: '어디서 가장 많이 걸려서 망하나? →', target: 'sbbq13' },
      },
    ],
  },
  sbbq5: {
    brand: null,
    title: '얼마 드나?',
    sub: '총 7,575만원 (올리브치킨 기준)',
    breadcrumb: ['BBQ', '얼마 드나?'],
    cards: [
      {
        title: '가맹비',
        hint: '계약 시 일시납',
        val: '1,100만원',
        valColor: 'yellow',
        row1Val: '1,100만원 일시납 (올리브치킨, VAT 포함)',
        row1Label: '2년 계약 · 2년 단위 갱신',
        tags: [
          { label: 'BSK(소형)는 550만', type: 'neu' },
          { label: '환불 조건 까다로움', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '1,100만 원 (올리브치킨 기준)이에요.' },
          { dot: 'gold', text: '가맹 이야기는 숫자로 봐야 해요. 말보다 계약서와 비용표가 중요해요.', source: '법률타임스' },
        ],
        qBtn: { label: '계약 취소하면 돈 돌려받을 수 있어? →', target: 'sbbq13' },
      },
      {
        title: '인테리어',
        hint: '타입별 편차 매우 큼',
        val: '3,135만원',
        valColor: 'yellow',
        row1Val: '15평(올리브치킨) 기준 3,135만원',
        row1Label: '3.3㎡당 209만원',
        tags: [
          { label: 'BSK(8평) 1,408만', type: 'neu' },
          { label: '빌리지(100평) 3억3천만', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '15평(올리브치킨) 기준 3,135만 원이에요.' },
          { dot: 'gold', text: '가맹은 시작보다 유지가 중요해요. 처음 돈보다 매달 나가는 돈을 봐야 해요.', source: '인사이트코리아' },
        ],
        qBtn: { label: '타입 고를 때 인테리어 비용이 결정적이야? →', target: 'sbbq13' },
      },
      {
        title: '장비/설비',
        hint: '주방 장비 일체',
        val: '2,420만원',
        valColor: 'yellow',
        row1Val: '2,420만원 (올리브치킨 기준)',
        row1Label: '타입별 2,020만~1억1,000만 차이 큼',
        tags: [
          { label: 'BSK 2,020만', type: 'neu' },
          { label: '빌리지 1억1,000만', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '올리브치킨 주방기기·집기 2,420만이에요.' },
          { dot: 'gold', text: '분쟁 키워드는 작게 봐도 됩니다. 대신 계약 전에는 크게 봐야 해요.', source: '포인트데일리' },
        ],
        qBtn: { label: '3년마다 또 수천만이 나간다고? →', target: 'sbbq9' },
      },
      {
        title: '숨겨진 비용',
        hint: '보증금 + 예비금',
        val: '+2천만+',
        valColor: 'yellow',
        row1Val: '보증금 500만 + 예비금 별도',
        row1Label: '전기·가스·냉난방 등 공개 외 별도',
        tags: [
          { label: '보증금 500만 (공식)', type: 'warn' },
          { label: '예비금 2,000만+', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '보증금은 3사 중 가장 낮은 500만이에요.' },
          { dot: 'gold', text: '가격은 묶였어요. 대신 비용 부담은 어딘가에 남아요.', source: '디스커버리뉴스' },
        ],
        qBtn: { label: '돈 모자라면 정확히 어느 순간 망해? →', target: 'sbbq13' },
      },
    ],
  },
  sbbq9: {
    brand: null,
    title: '얼마 남나?',
    sub: '월 순이익 약 340만 (20평·직원1명)',
    breadcrumb: ['BBQ', '얼마 남나?'],
    cards: [
      {
        title: '재료비',
        hint: '매출의 고정 비율',
        val: '-532만원',
        valColor: 'red',
        row1Val: '매출의 38% 고정',
        row1Label: '본사 공급 88% · 절감 불가',
        tags: [
          { label: '절감 여지 없음', type: 'warn' },
          { label: '매출 줄어도 고정', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '매출의 38%, 올리브유라 원가 높아요.' },
          { dot: 'gold', text: '본사에서 88% 사야 해서 줄일 수 없어요.' },
        ],
        qBtn: { label: '본사가 단가 올리면 내가 다 떠안아? →', target: 'sbbq13' },
      },
      {
        title: '인건비',
        hint: '직원 1명 기준',
        val: '-250만원',
        valColor: 'red',
        row1Val: '250만원 기본',
        row1Label: '주말 알바 +80만 추가 가능',
        tags: [
          { label: '1인 운영 불가', type: 'warn' },
          { label: '매년 상승', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '직원 1명 기준 250만 원이에요.' },
          { dot: 'gold', text: '가격 얘기가 나왔어요. 손님도 점주도 계산기를 두드리는 구간이에요.', source: '세계일보' },
        ],
        qBtn: { label: '혼자 다 하면 1~2년 안에 번아웃 온다고? →', target: 'sbbq13' },
      },
      {
        title: '광고비',
        hint: '원재료 단위당 부과',
        val: '300~400원/마리',
        valColor: 'green',
        row1Val: '마리당 300원(상반기)·400원(하반기)',
        row1Label: '별도 로열티 없음 — 광고비만 부과',
        tags: [
          { label: '로열티 없음 (정보공개서 명시)', type: 'ok' },
          { label: '마리당 광고비만 부과', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '가맹은 시작보다 유지가 중요해요. 처음 돈보다 매달 나가는 돈을 봐야 해요.', source: '인사이트코리아' },
          { dot: 'gold', text: '마리당 광고비 300~400원만 부과돼요.' },
        ],
        qBtn: { label: '로열티 없으면 어디서 본사가 마진 가져가? →', target: 'sbbq5' },
      },
      {
        title: '실제 순이익',
        hint: '모든 비용 제외 후',
        val: '약 340만원',
        valColor: 'yellow',
        row1Val: '약 340만원',
        row1Label: '매출 1,400만 · 직원 1명 기준',
        tags: [
          { label: '직원 2명 → 120만대', type: 'warn' },
          { label: '매출 1,700만 → 480만', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '잘 되면 한 달에 340만 남아요.' },
          { dot: 'gold', text: '브랜드 힘은 있어요. 비싼 이미지를 버틸 상권인지가 문제예요.', source: '아주경제' },
        ],
        qBtn: { label: '불황 오면 매출이 얼마나 빠져? →', target: 'sbbq13' },
      },
    ],
  },
  sbbq13: {
    brand: null,
    title: '어디서 망하나?',
    sub: '오픈 6개월이 가장 위험한 구간',
    breadcrumb: ['BBQ', '어디서 망하나?'],
    cards: [
      {
        title: '가격 저항',
        hint: '폐업 원인 1위',
        val: '32%',
        valColor: 'red',
        row1Val: '폐업의 32%',
        row1Label: '프리미엄 가격에 소비자 이탈',
        tags: [
          { label: '경기 민감도 높음', type: 'warn' },
          { label: '상권 선택 핵심', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '이미지는 좋아져요. 그래도 점주에게 중요한 건 결국 하루 매출이에요.', source: '반론보도' },
          { dot: 'gold', text: '불황 오면 3사 중 매출이 제일 빠져요.' },
        ],
        qBtn: { label: '어떤 상권이 BBQ에 맞아? →', target: 'sbbq1' },
      },
      {
        title: '입지 실패',
        hint: '폐업 원인 2위',
        val: '31%',
        valColor: 'red',
        row1Val: '폐업의 31%',
        row1Label: '상권 소득 수준 미스매치',
        tags: [
          { label: '저소득 상권 위험', type: 'warn' },
          { label: '조사 최소 3회', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '브랜드 힘은 있어요. 비싼 이미지를 버틸 상권인지가 문제예요.', source: '파이낸셜투데이' },
          { dot: 'gold', text: '가격 얘기가 나왔어요. 손님도 점주도 계산기를 두드리는 구간이에요.', source: '1코노미뉴스' },
        ],
        qBtn: { label: '오픈하고 나면 입지는 못 바꾼다고? →', target: 'sbbq1' },
      },
      {
        title: '자금 소진',
        hint: '초기 운영 위기',
        val: '25%',
        valColor: 'red',
        row1Val: '오픈 3개월차 최대 위험',
        row1Label: '초기 투자비 회수 기간 길어짐',
        tags: [
          { label: '예비금 3천 필수', type: 'warn' },
          { label: '대출이자 포함 계획', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '오픈 1~2개월은 손님이 몰려요.' },
          { dot: 'gold', text: '손익분기까지 5~7개월 버텨야 해요.' },
        ],
        qBtn: { label: '3개월 버티는 데 돈이 얼마나 필요해? →', target: 'sbbq5' },
      },
      {
        title: '본사 갈등',
        hint: '계약 분쟁',
        val: '12%',
        valColor: 'yellow',
        row1Val: '폐업의 12%',
        row1Label: '계약서 안 보면 당함',
        tags: [
          { label: '단가 연 2~4% 강제 인상', type: 'warn' },
          { label: '해지 조건 까다로움', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '가맹 이야기는 숫자로 봐야 해요. 말보다 계약서와 비용표가 중요해요.', source: '한국청년일보' },
          { dot: 'gold', text: '분쟁 키워드는 작게 봐도 됩니다. 대신 계약 전에는 크게 봐야 해요.', source: '포인트데일리' },
        ],
        qBtn: { label: '그만두고 싶어도 못 나온다고? →', target: 'sbbq5' },
      },
    ],
  },
  spura1: {
    brand: null,
    title: '해볼 만할까?',
    sub: '4가지 핵심으로 파악',
    breadcrumb: ['푸라닭', '해볼 만할까?'],
    cards: [
      {
        title: '브랜드 파워',
        hint: '치킨 시장 인지도',
        val: '중하위',
        valColor: 'yellow',
        row1Val: '인지도 60%',
        row1Label: '재방문율 55% · 허브치킨 마니아층',
        tags: [
          { label: '마니아층 존재', type: 'ok' },
          { label: '자연 집객 약함', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '브랜드는 계속 새 이야기를 만듭니다. 점주는 그 이야기가 매출로 이어지는지 봐야 해요.', source: '신아일보' },
          { dot: 'gold', text: '논란은 지나갈 수 있어요. 하지만 브랜드 신뢰는 한 번 흔들리면 오래 가요.', source: '인더뉴스' },
        ],
        qBtn: { label: '인지도 낮으면 오픈 초기 어때? →', target: 'spura13' },
      },
      {
        title: '초보자 난이도',
        hint: '시스템화 수준',
        val: '낮음',
        valColor: 'green',
        row1Val: '교육 2~3주 후 운영',
        row1Label: '메뉴 단순 · 매뉴얼 완성도 중상',
        tags: [
          { label: '레시피 표준화', type: 'ok' },
          { label: '소규모 운영 가능', type: 'ok' },
        ],
        insights: [
          { dot: 'teal', text: '2~3주면 혼자 돌릴 수 있어요.' },
          { dot: 'gold', text: '가맹 이야기는 숫자로 봐야 해요. 말보다 계약서와 비용표가 중요해요.', source: '스트레이트뉴스' },
        ],
        qBtn: { label: '소규모로 혼자 운영할 수 있어? →', target: 'spura9' },
      },
      {
        title: '경쟁 강도',
        hint: '주변 밀집도',
        val: '높음',
        valColor: 'red',
        row1Val: '반경 500m 내 4.2개',
        row1Label: '치킨집 전국 8.7만개',
        tags: [
          { label: '동일브랜드 500m 보호', type: 'ok' },
          { label: '3대 브랜드와 경쟁', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '같은 푸라닭은 500m 안에 못 열어요.' },
          { dot: 'gold', text: '이름은 잘 알려져 있어요. 알려진 만큼 비교도 많이 당해요.', source: '세계일보' },
        ],
        qBtn: { label: '브랜드 약한데 경쟁에서 살아남으려면? →', target: 'spura13' },
      },
      {
        title: '폐업 위험도',
        hint: '업계 통계 기반',
        val: '주의 필요',
        valColor: 'red',
        row1Val: '3년 내 폐업률 33%',
        row1Label: '집객 실패가 최대 위험',
        tags: [
          { label: '집객 부족 1위', type: 'warn' },
          { label: '입지 실패 2위', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '가격 얘기가 나왔어요. 손님도 점주도 계산기를 두드리는 구간이에요.', source: '서울경제TV' },
          { dot: 'gold', text: '3년 안에 10명 중 3명 문 닫아요.' },
        ],
        qBtn: { label: '어디서 가장 많이 걸려서 망하나? →', target: 'spura13' },
      },
    ],
  },
  spura5: {
    brand: null,
    title: '얼마 드나?',
    sub: '총 9천 ~ 최대 1억 2천',
    breadcrumb: ['푸라닭', '얼마 드나?'],
    cards: [
      {
        title: '가맹비',
        hint: '계약 시 일시납',
        val: '1,100만원',
        valColor: 'yellow',
        row1Val: '1,100만원 일시납 (VAT 포함)',
        row1Label: '3년 계약 · 2년 단위 갱신',
        tags: [
          { label: '교촌·BBQ와 동일 1,100만', type: 'neu' },
          { label: '환불 조건 확인 필요', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '1,100만 원, 교육비 550만 별도예요.' },
          { dot: 'gold', text: '보증금 없음 — 4사 중 유일해요.' },
        ],
        qBtn: { label: '보증금 없다는 게 진짜야? →', target: 'spura1' },
      },
      {
        title: '인테리어',
        hint: '소규모 배달형 기준',
        val: '1,880만원',
        valColor: 'green',
        row1Val: '33㎡ 기준 1,880만원',
        row1Label: '3.3㎡당 188만원',
        tags: [
          { label: '3대 브랜드 대비 절반 이하', type: 'ok' },
          { label: '매장 구조 따라 달라짐', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '33㎡ 기준 1,880만 원이에요.' },
          { dot: 'gold', text: 'BBQ 올리브치킨(3,135만)보다 훨씬 싸요.' },
        ],
        qBtn: { label: '인테리어 싸면 품질이 달라? →', target: 'spura13' },
      },
      {
        title: '장비/설비',
        hint: '주방 장비 일체',
        val: '3,500만원',
        valColor: 'yellow',
        row1Val: '3,500만원',
        row1Label: '튀김기·냉장·POS 포함',
        tags: [
          { label: '튀김기 3년 교체', type: 'warn' },
          { label: 'POS 250만', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '이미지는 뚜렷해요. 하지만 손님을 계속 불러오는 힘은 따로 봐야 해요.', source: '베이비뉴스' },
          { dot: 'gold', text: '튀김기는 3년 되면 또 사야 해요.' },
        ],
        qBtn: { label: '장비 싸면 품질도 다른 거야? →', target: 'spura1' },
      },
      {
        title: '숨겨진 비용',
        hint: '보증금 없음 (4사 유일)',
        val: '+예비금만',
        valColor: 'green',
        row1Val: '보증금 없음 + 운영 예비금 별도',
        row1Label: '서울보증보험 가입으로 대체',
        tags: [
          { label: '보증금 없음 (4사 유일)', type: 'ok' },
          { label: '예비금 2,000만+', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '가맹 이야기는 숫자로 봐야 해요. 말보다 계약서와 비용표가 중요해요.', source: '연합뉴스' },
          { dot: 'gold', text: '할인은 손님을 부릅니다. 대신 남는 돈도 같이 깎일 수 있어요.', source: '테크M' },
        ],
        qBtn: { label: '보증금 없으면 진짜 1억으로 창업 가능해? →', target: 'spura13' },
      },
    ],
  },
  spura9: {
    brand: null,
    title: '얼마 남나?',
    sub: '월 순이익 약 200~350만 (연 평균매출 기준)',
    breadcrumb: ['푸라닭', '얼마 남나?'],
    cards: [
      {
        title: '재료비',
        hint: '매출의 고정 비율',
        val: '-380만원',
        valColor: 'red',
        row1Val: '매출의 38% 고정',
        row1Label: '본사 공급 80% · 절감 여지 소폭',
        tags: [
          { label: '절감 여지 제한적', type: 'warn' },
          { label: '허브재료 단가 높음', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '가맹 이야기는 숫자로 봐야 해요. 말보다 계약서와 비용표가 중요해요.', source: '세계비즈' },
          { dot: 'gold', text: '가격 얘기가 나왔어요. 손님도 점주도 계산기를 두드리는 구간이에요.', source: '한국피아이뉴스' },
        ],
        qBtn: { label: '허브재료 비싸면 원가가 더 높아? →', target: 'spura13' },
      },
      {
        title: '인건비',
        hint: '직원 1명 기준',
        val: '-200만원',
        valColor: 'yellow',
        row1Val: '200만원 기본',
        row1Label: '소규모 매장 · 파트타임 활용 가능',
        tags: [
          { label: '소규모 운영 유리', type: 'ok' },
          { label: '매년 상승', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '브랜드는 계속 새 이야기를 만듭니다. 점주는 그 이야기가 매출로 이어지는지 봐야 해요.', source: '더파워뉴스' },
          { dot: 'gold', text: '직원 1명 기준 200만 원이에요.' },
        ],
        qBtn: { label: '파트타임으로 운영하면 품질 유지돼? →', target: 'spura1' },
      },
      {
        title: '임대료',
        hint: '15평 평균',
        val: '-120만원',
        valColor: 'green',
        row1Val: '평균 120만원',
        row1Label: '소규모 매장 · 임대료 부담 낮음',
        tags: [
          { label: '소규모 상권 가능', type: 'ok' },
          { label: '권리금 별도', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '이름은 잘 알려져 있어요. 알려진 만큼 비교도 많이 당해요.', source: '세계일보' },
          { dot: 'gold', text: '이미지는 뚜렷해요. 하지만 손님을 계속 불러오는 힘은 따로 봐야 해요.', source: '베이비뉴스' },
        ],
        qBtn: { label: '주택가에서도 장사가 돼? →', target: 'spura1' },
      },
      {
        title: '실제 순이익',
        hint: '모든 비용 제외 후',
        val: '약 280만원',
        valColor: 'yellow',
        row1Val: '약 200~350만원',
        row1Label: '연 평균매출 4.5억 기준 추정',
        tags: [
          { label: '순이익률 7~10%', type: 'neu' },
          { label: '4사 중 최저 수준', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '평균 가맹점 기준 월 200~350만 남아요.' },
          { dot: 'gold', text: '가격 얘기가 나왔어요. 손님도 점주도 계산기를 두드리는 구간이에요.', source: '포인트데일리' },
        ],
        qBtn: { label: '월 280인데 투자금 회수에 몇 년 걸려? →', target: 'spura5' },
      },
    ],
  },
  spura13: {
    brand: null,
    title: '어디서 망하나?',
    sub: '오픈 6개월이 가장 위험한 구간',
    breadcrumb: ['푸라닭', '어디서 망하나?'],
    cards: [
      {
        title: '집객 부족',
        hint: '폐업 원인 1위',
        val: '40%',
        valColor: 'red',
        row1Val: '폐업의 40%',
        row1Label: '브랜드 파워 부재로 직격탄',
        tags: [
          { label: 'SNS 마케팅 필수', type: 'warn' },
          { label: '배달앱 광고비 부담', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '브랜드는 계속 새 이야기를 만듭니다. 점주는 그 이야기가 매출로 이어지는지 봐야 해요.', source: '신아일보' },
          { dot: 'gold', text: '할인은 손님을 부릅니다. 대신 남는 돈도 같이 깎일 수 있어요.', source: '로이슈' },
        ],
        qBtn: { label: '마케팅 안 하면 얼마나 빨리 망해? →', target: 'spura9' },
      },
      {
        title: '입지 실패',
        hint: '폐업 원인 2위',
        val: '30%',
        valColor: 'red',
        row1Val: '폐업의 30%',
        row1Label: '유동인구 없는 상권 오픈',
        tags: [
          { label: '배달 상권 필수', type: 'warn' },
          { label: '조사 최소 3회', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '이미지는 뚜렷해요. 하지만 손님을 계속 불러오는 힘은 따로 봐야 해요.', source: '베이비뉴스' },
          { dot: 'gold', text: '이름은 잘 알려져 있어요. 알려진 만큼 비교도 많이 당해요.', source: '세계일보' },
        ],
        qBtn: { label: '오픈하고 나면 입지는 못 바꾼다고? →', target: 'spura1' },
      },
      {
        title: '자금 소진',
        hint: '초기 운영 위기',
        val: '20%',
        valColor: 'yellow',
        row1Val: '오픈 3~4개월차 위험',
        row1Label: '집객 안 되면 예비금 빠르게 소진',
        tags: [
          { label: '예비금 2천 필수', type: 'warn' },
          { label: '마케팅비 예산 확보', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '초기비용은 3사보다 적어요.' },
          { dot: 'gold', text: '가격 얘기가 나왔어요. 손님도 점주도 계산기를 두드리는 구간이에요.', source: '한국피아이뉴스' },
        ],
        qBtn: { label: '예비금 없으면 언제 망해? →', target: 'spura5' },
      },
      {
        title: '번아웃 폐업',
        hint: '체력·정신 소모',
        val: '10%',
        valColor: 'yellow',
        row1Val: '폐업의 10%',
        row1Label: '마케팅+운영 이중 부담',
        tags: [
          { label: '마케팅 직접 해야 함', type: 'warn' },
          { label: '운영+홍보 이중 소모', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '가맹 이야기는 숫자로 봐야 해요. 말보다 계약서와 비용표가 중요해요.', source: '에코노빌' },
          { dot: 'gold', text: '논란은 지나갈 수 있어요. 하지만 브랜드 신뢰는 한 번 흔들리면 오래 가요.', source: '인더뉴스' },
        ],
        qBtn: { label: '월 220 벌려고 이 고생을 해야 해? →', target: 'spura9' },
      },
    ],
  },
}
