export const screens = {
  s0: {
    brand: null,
    title: '어느 브랜드가 궁금해?',
    sub: '브랜드를 선택하면 핵심만 빠르게 파고듭니다',
    breadcrumb: null,
    cards: [
      {
        title: '교촌치킨',
        hint: '업계 1위 · 간장치킨 강자',
        val: '업계 1위',
        valColor: 'green',
        row1Val: '가맹점 수 1,300+',
        row1Label: '업계 최다 · 간장·허니 시리즈 강세',
        tags: [
          { label: '브랜드 1위', type: 'ok' },
          { label: '가맹비 높음', type: 'warn' },
          { label: '자금 2억+', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '1위 브랜드, 간판이 손님 데려와요.' },
          { dot: 'gold', text: '2억 넘게 써야 시작할 수 있어요.' },
        ],
        qBtn: { label: '브랜드 최강인데 왜 2억을 써야 해?', target: 'sgyo0' },
      },
      {
        title: '비비큐(BBQ)',
        hint: '업계 2위 · 황금올리브치킨',
        val: '업계 2위',
        valColor: 'green',
        row1Val: '가맹점 수 1,500+',
        row1Label: '해외 진출 · 프리미엄 포지셔닝',
        tags: [
          { label: '브랜드 2위', type: 'ok' },
          { label: '가격 프리미엄', type: 'neu' },
          { label: '로열티 부담', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '50개국 나간 이름, 손님이 알아서 와요.' },
          { dot: 'gold', text: '마리 2만 원대, 잘 팔리지만 눈치 봐요.' },
        ],
        qBtn: { label: '비싼 치킨, 불황 오면 첫 번째로 망한다고?', target: 'sbbq0' },
      },
      {
        title: 'BHC치킨',
        hint: '업계 3위 · 뿌링클 강세',
        val: '업계 3위',
        valColor: 'yellow',
        row1Val: '가맹점 수 1,700+',
        row1Label: '뿌링클·맛초킹 · 배달 강세',
        tags: [
          { label: '브랜드 3위', type: 'neu' },
          { label: '자금 1.5억+', type: 'warn' },
          { label: '초보 가능', type: 'ok' },
        ],
        insights: [
          { dot: 'teal', text: '매뉴얼 잘 돼있어 처음도 할 수 있어요.' },
          { dot: 'gold', text: '1.5억 써야 해요. 3개월이 고비예요.' },
        ],
        qBtn: { label: '초보도 된다는데, 1.5억 쓰고 월 280이 전부야?', target: 'sbhc0' },
      },
      {
        title: '푸라닭치킨',
        hint: '중견 브랜드 · 허브치킨',
        val: '소자본 가능',
        valColor: 'green',
        row1Val: '가맹점 수 500+',
        row1Label: '허브시리즈 · 소규모 매장 가능',
        tags: [
          { label: '초기비용 낮음', type: 'ok' },
          { label: '브랜드 인지도↓', type: 'warn' },
          { label: '소자본 창업', type: 'ok' },
        ],
        insights: [
          { dot: 'teal', text: '1억 미만으로 시작할 수 있어요.' },
          { dot: 'gold', text: '이름이 약해서 손님을 직접 모아야 해요.' },
        ],
        qBtn: { label: '1억으로 치킨집, 진짜 될까?', target: 'spura0' },
      },
    ],
  },
  sbhc0: {
    brand: 'BHC 치킨',
    title: '뭐가 궁금해?',
    sub: '핵심만 빠르게 파고드세요',
    breadcrumb: null,
    cards: [
      {
        title: '해볼 만할까?',
        brandKey: 'BHC치킨',
        hint: '솔직한 한 줄 평가',
        val: '중상',
        valColor: 'yellow',
        row1Val: '종합 평가: 중상',
        row1Label: '초보 진입 가능 · 브랜드 3위 · 자금 부담 큼',
        tags: [
          { label: '초보자 가능', type: 'ok' },
          { label: '자금 1.5억+', type: 'warn' },
          { label: '브랜드 3위', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '초보도 배워서 할 수 있는 구조예요.' },
          { dot: 'gold', text: '2억 못 채우면 3개월이 고비예요.' },
        ],
        qBtn: { label: '3개월 안에 위기 온다는데, 진짜야? →', target: 's1' },
      },
      {
        title: '얼마 드나?',
        brandKey: 'BHC치킨',
        hint: '초기 투자 현실적으로',
        val: '1억 5천',
        valColor: 'red',
        row1Val: '총 1억 5,000만원',
        row1Label: '보증금 포함 시 최대 2억',
        tags: [
          { label: '가맹비 900만', type: 'warn' },
          { label: '인테리어 6.5천', type: 'warn' },
          { label: '예비금 별도', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '총 1.5억, 공개된 금액이에요.' },
          { dot: 'gold', text: '보증금·예비금 더하면 2억 돼요.' },
        ],
        qBtn: { label: '1억 5천인데 왜 2억이 필요하다고? →', target: 's5' },
      },
      {
        title: '얼마 남나?',
        brandKey: 'BHC치킨',
        hint: '한 달 실제 순이익',
        val: '약 280만',
        valColor: 'yellow',
        row1Val: '월 순이익 280만원',
        row1Label: '매출 1,200만 · 직원 1명 기준',
        tags: [
          { label: '재료비 -456만', type: 'warn' },
          { label: '인건비 -250만', type: 'warn' },
          { label: '임대료 -150만', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '잘 되면 한 달에 280만 남아요.' },
          { dot: 'gold', text: '직원 한 명 더 쓰면 100만대예요.' },
        ],
        qBtn: { label: '열심히 해도 월 280이 전부야? →', target: 's9' },
      },
      {
        title: '어디서 망하나?',
        brandKey: 'BHC치킨',
        hint: '폐업 패턴 분석',
        val: '입지 1위',
        valColor: 'red',
        row1Val: '입지 실패 38%',
        row1Label: '오픈 후 3~6개월이 최대 위험',
        tags: [
          { label: '입지 38%', type: 'warn' },
          { label: '자금 31%', type: 'warn' },
          { label: '본사갈등 18%', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '망하는 이유 1위는 자리예요.' },
          { dot: 'gold', text: '오픈 3~6개월이 가장 위험해요.' },
        ],
        qBtn: { label: '10명 중 3명이 망한다고? →', target: 's13' },
      },
    ],
  },
  s1: {
    brand: null,
    title: '해볼 만할까?',
    sub: '4가지 핵심으로 파악',
    breadcrumb: ['BHC', '해볼 만할까?'],
    cards: [
      {
        title: '브랜드 파워',
        hint: '치킨 시장 인지도',
        val: '상위 3위',
        valColor: 'green',
        row1Val: '인지도 98%',
        row1Label: '재방문율 62% · 배달앱 상위 5%',
        tags: [
          { label: '자연 집객 가능', type: 'ok' },
          { label: '로열티 2~3%', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: 'TV에 자주 나와서 이름을 알아요.' },
          { dot: 'gold', text: '로열티가 매달 2~3% 빠져나가요.' },
        ],
        qBtn: { label: '브랜드 좋은데 왜 30%가 망해? →', target: 's13' },
      },
      {
        title: '초보자 난이도',
        hint: '시스템화 수준',
        val: '낮음',
        valColor: 'green',
        row1Val: '교육 3주 후 운영',
        row1Label: '매뉴얼 완성도 상',
        tags: [
          { label: '레시피 표준화', type: 'ok' },
          { label: '1인 운영 불가', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '3주 교육 받으면 혼자 돌려요.' },
          { dot: 'gold', text: '사람 없이 혼자는 못 해요.' },
        ],
        qBtn: { label: '쉽다더니 왜 혼자는 못 하나? →', target: 's9' },
      },
      {
        title: '경쟁 강도',
        hint: '주변 밀집도',
        val: '높음',
        valColor: 'red',
        row1Val: '반경 500m 내 4.2개',
        row1Label: '치킨집 전국 8.7만개',
        tags: [
          { label: '동일브랜드 500m 보호', type: 'ok' },
          { label: '타브랜드 무제한', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '같은 BHC는 500m 안에 못 열어요.' },
          { dot: 'gold', text: '교촌·BBQ는 바로 옆도 가능해요.' },
        ],
        qBtn: { label: '치킨집이 편의점보다 많다고? →', target: 's13' },
      },
      {
        title: '폐업 위험도',
        hint: '업계 통계 기반',
        val: '주의 필요',
        valColor: 'red',
        row1Val: '3년 내 폐업률 30%',
        row1Label: '오픈 6개월이 최대 위험',
        tags: [
          { label: '입지 실패 1위', type: 'warn' },
          { label: '자금 소진 2위', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '사전 준비가 생존을 결정해요.' },
          { dot: 'gold', text: '3년 안에 10명 중 3명 문 닫아요.' },
        ],
        qBtn: { label: '어디서 가장 많이 걸려서 망하나? →', target: 's13' },
      },
    ],
  },
  s5: {
    brand: null,
    title: '얼마 드나?',
    sub: '총 1억 5천 ~ 최대 2억',
    breadcrumb: ['BHC', '얼마 드나?'],
    cards: [
      {
        title: '가맹비',
        hint: '계약 시 일시납',
        val: '900만원',
        valColor: 'yellow',
        row1Val: '900만원 일시납',
        row1Label: '5년 계약 · 갱신 시 재납부',
        tags: [
          { label: '교촌보다 100만 저렴', type: 'neu' },
          { label: '환불 조건 까다로움', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '900만 원, 3사 중 가장 싸요.' },
          { dot: 'gold', text: '한 달 안에만 일부 돌려받아요.' },
        ],
        qBtn: { label: '계약 취소하면 돈 돌려받을 수 있어? →', target: 's13' },
      },
      {
        title: '인테리어',
        hint: '본사 지정업체 강제',
        val: '6,500만원',
        valColor: 'red',
        row1Val: '평당 약 325만원',
        row1Label: '20평 기준 · 5년마다 리모델링',
        tags: [
          { label: '본사 마진 20~30%', type: 'warn' },
          { label: '직접 업체 불가', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '20평 기준 6,500만 원이에요.' },
          { dot: 'gold', text: '본사 업체만 써야 해요. 직접 못 해요.' },
        ],
        qBtn: { label: '6,500에 본사 마진 30%가 포함됐다고? →', target: 's13' },
      },
      {
        title: '장비/설비',
        hint: '주방 장비 일체',
        val: '4,800만원',
        valColor: 'red',
        row1Val: '4,800만원',
        row1Label: '튀김기·냉장·POS 포함',
        tags: [
          { label: '튀김기 3년 교체', type: 'warn' },
          { label: 'POS 300만', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '튀김기·냉장·POS 포함 4,800만이에요.' },
          { dot: 'gold', text: '튀김기는 3년 되면 또 사야 해요.' },
        ],
        qBtn: { label: '3년마다 또 수천만이 나간다고? →', target: 's9' },
      },
      {
        title: '숨겨진 비용',
        hint: '보증금 + 예비금',
        val: '+5천만 이상',
        valColor: 'red',
        row1Val: '최소 5,500만 추가',
        row1Label: '공개 금액 외 별도',
        tags: [
          { label: '보증금 2,500만~', type: 'warn' },
          { label: '예비금 3,000만', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '공개 금액 외에 5,500만 더 필요해요.' },
          { dot: 'gold', text: '이 돈 없으면 3개월에 바닥나요.' },
        ],
        qBtn: { label: '돈 모자라면 정확히 어느 순간 망해? →', target: 's13' },
      },
    ],
  },
  s9: {
    brand: null,
    title: '얼마 남나?',
    sub: '월 순이익 약 280만 (20평·직원1명)',
    breadcrumb: ['BHC', '얼마 남나?'],
    cards: [
      {
        title: '재료비',
        hint: '매출의 고정 비율',
        val: '-456만원',
        valColor: 'red',
        row1Val: '매출의 38% 고정',
        row1Label: '본사 공급 85% · 절감 불가',
        tags: [
          { label: '절감 여지 없음', type: 'warn' },
          { label: '매출 줄어도 고정', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '매출의 38%, 줄일 방법이 없어요.' },
          { dot: 'gold', text: '본사에서 85% 사야 해서 고정이에요.' },
        ],
        qBtn: { label: '본사가 단가 올리면 내가 다 떠안아? →', target: 's13' },
      },
      {
        title: '인건비',
        hint: '직원 1명 기준',
        val: '-250만원',
        valColor: 'red',
        row1Val: '250만원 기본',
        row1Label: '주말 알바 +80만 추가 가능',
        tags: [
          { label: '1인 운영 불가', type: 'warn' },
          { label: '매년 상승', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '직원 1명 기준 250만 원이에요.' },
          { dot: 'gold', text: '최저임금 오를 때마다 같이 올라요.' },
        ],
        qBtn: { label: '혼자 다 하면 1~2년 안에 번아웃 온다고? →', target: 's13' },
      },
      {
        title: '임대료',
        hint: '20평 평균',
        val: '-150만원',
        valColor: 'yellow',
        row1Val: '평균 150만원',
        row1Label: '상권에 따라 50~500만 차이',
        tags: [
          { label: '200만 되면 반토막', type: 'warn' },
          { label: '권리금 별도', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '월 1,050만 매출이 손익 기준이에요.' },
          { dot: 'gold', text: '임대료 50만 차이가 순이익 반 날려요.' },
        ],
        qBtn: { label: '임대 50만 차이가 순이익을 반으로 만든다고? →', target: 's13' },
      },
      {
        title: '실제 순이익',
        hint: '모든 비용 제외 후',
        val: '약 280만원',
        valColor: 'yellow',
        row1Val: '약 280만원',
        row1Label: '매출 1,200만 · 직원 1명 기준',
        tags: [
          { label: '직원 2명 → 100만대', type: 'warn' },
          { label: '매출 1,500만 → 420만', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '매출 200만 올리면 순이익 50% 올라요.' },
          { dot: 'gold', text: '직원 한 명 더 쓰면 100만대로 줄어요.' },
        ],
        qBtn: { label: '직원 한 명 더 쓰면 남는 게 없다고? →', target: 's13' },
      },
    ],
  },
  s13: {
    brand: null,
    title: '어디서 망하나?',
    sub: '오픈 6개월이 가장 위험한 구간',
    breadcrumb: ['BHC', '어디서 망하나?'],
    cards: [
      {
        title: '입지 실패',
        hint: '폐업 원인 1위',
        val: '38%',
        valColor: 'red',
        row1Val: '폐업의 38%',
        row1Label: '사전 조사가 생존을 결정',
        tags: [
          { label: '배달vs홀 미스매치', type: 'warn' },
          { label: '조사 최소 3회', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '망하는 이유 1위, 자리 잘못 잡은 거예요.' },
          { dot: 'gold', text: '배달 상권에 홀 인테리어하면 망해요.' },
        ],
        qBtn: { label: '오픈하고 나면 입지는 못 바꾼다고? →', target: 's1' },
      },
      {
        title: '자금 소진',
        hint: '초기 운영 위기',
        val: '31%',
        valColor: 'red',
        row1Val: '오픈 3개월차 최대 위험',
        row1Label: '오픈 버프 끝나는 시점',
        tags: [
          { label: '예비금 3천 필수', type: 'warn' },
          { label: '대출이자 포함 계획', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '오픈 1~2개월은 손님이 몰려요.' },
          { dot: 'gold', text: '3~4개월차에 돈이 제일 많이 나가요.' },
        ],
        qBtn: { label: '3개월 버티는 데 돈이 얼마나 필요해? →', target: 's5' },
      },
      {
        title: '본사 갈등',
        hint: '계약 분쟁',
        val: '18%',
        valColor: 'yellow',
        row1Val: '폐업의 18%',
        row1Label: '계약서 안 보면 당함',
        tags: [
          { label: '단가 연 2~5% 강제 인상', type: 'warn' },
          { label: '해지 조건 까다로움', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '메뉴·가격 다 본사가 정해요.' },
          { dot: 'gold', text: '나가고 싶어도 위약금이 수천만이에요.' },
        ],
        qBtn: { label: '그만두고 싶어도 못 나온다고? →', target: 's5' },
      },
      {
        title: '번아웃 폐업',
        hint: '체력·정신 소모',
        val: '13%',
        valColor: 'yellow',
        row1Val: '폐업의 13%',
        row1Label: '주 7일 장시간 노동',
        tags: [
          { label: '1인 운영 시 고위험', type: 'warn' },
          { label: '1~2년 내 한계', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '치킨은 주 7일, 하루 12시간이에요.' },
          { dot: 'gold', text: '1~2년차에 체력 한계 오는 경우 많아요.' },
        ],
        qBtn: { label: '월 280 벌려고 주 7일 일하는 거 맞아? →', target: 's9' },
      },
    ],
  },
  sgyo0: {
    brand: '교촌치킨',
    title: '뭐가 궁금해?',
    sub: '핵심만 빠르게 파고드세요',
    breadcrumb: null,
    cards: [
      {
        title: '해볼 만할까?',
        brandKey: '교촌치킨',
        hint: '솔직한 한 줄 평가',
        val: '중상',
        valColor: 'yellow',
        row1Val: '종합 평가: 중상',
        row1Label: '브랜드 1위 · 초기비용 최고 · 본사 통제 강함',
        tags: [
          { label: '브랜드 1위', type: 'ok' },
          { label: '자금 2억+', type: 'warn' },
          { label: '본사 통제 강함', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '업계 1위, 이름 하나는 최강이에요.' },
          { dot: 'gold', text: '2억 넘게 쓰고 본사 규정도 빡빡해요.' },
        ],
        qBtn: { label: '브랜드 1위인데 왜 통제가 강하다고? →', target: 'sgyo1' },
      },
      {
        title: '얼마 드나?',
        brandKey: '교촌치킨',
        hint: '초기 투자 현실적으로',
        val: '2억 이상',
        valColor: 'red',
        row1Val: '총 2억~2.5억원',
        row1Label: '보증금·예비금 포함 시 최대 2.5억',
        tags: [
          { label: '가맹비 1,000만', type: 'warn' },
          { label: '인테리어 8천+', type: 'warn' },
          { label: '예비금 별도', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '총 2억~2.5억, 3사 중 가장 비싸요.' },
          { dot: 'gold', text: '공개 금액 외 숨겨진 비용이 꽤 있어요.' },
        ],
        qBtn: { label: '왜 교촌이 가장 비싼 거야? →', target: 'sgyo5' },
      },
      {
        title: '얼마 남나?',
        brandKey: '교촌치킨',
        hint: '한 달 실제 순이익',
        val: '약 320만',
        valColor: 'yellow',
        row1Val: '월 순이익 320만원',
        row1Label: '매출 1,300만 · 직원 1명 기준',
        tags: [
          { label: '재료비 -494만', type: 'warn' },
          { label: '인건비 -250만', type: 'warn' },
          { label: '임대료 -150만', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '잘 되면 한 달에 320만 남아요.' },
          { dot: 'gold', text: '재료비·로열티 비율 높아 실속이 적어요.' },
        ],
        qBtn: { label: '객단가 높은데 왜 순이익이 별로야? →', target: 'sgyo9' },
      },
      {
        title: '어디서 망하나?',
        brandKey: '교촌치킨',
        hint: '폐업 패턴 분석',
        val: '자금 1위',
        valColor: 'red',
        row1Val: '자금 소진 35%',
        row1Label: '높은 초기비용이 가장 큰 리스크',
        tags: [
          { label: '자금 35%', type: 'warn' },
          { label: '입지 33%', type: 'warn' },
          { label: '본사갈등 20%', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '자금 소진이 망하는 이유 1위예요.' },
          { dot: 'gold', text: '2억 쓰고 손익분기 전에 바닥나요.' },
        ],
        qBtn: { label: '2억 넘게 쓰고 망하면 얼마나 날아가? →', target: 'sgyo13' },
      },
    ],
  },
  sgyo1: {
    brand: null,
    title: '해볼 만할까?',
    sub: '4가지 핵심으로 파악',
    breadcrumb: ['교촌', '해볼 만할까?'],
    cards: [
      {
        title: '브랜드 파워',
        hint: '치킨 시장 인지도',
        val: '업계 1위',
        valColor: 'green',
        row1Val: '인지도 99%',
        row1Label: '재방문율 68% · 배달앱 상위 3%',
        tags: [
          { label: '자연 집객 최강', type: 'ok' },
          { label: '로열티 2%', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '인지도 99%, 간장치킨 하면 교촌이에요.' },
          { dot: 'gold', text: '로열티가 매달 2% 빠져나가요.' },
        ],
        qBtn: { label: '브랜드 최강인데 왜 비용도 최강이야? →', target: 'sgyo5' },
      },
      {
        title: '초보자 난이도',
        hint: '시스템화 수준',
        val: '보통',
        valColor: 'yellow',
        row1Val: '교육 4주 후 운영',
        row1Label: '메뉴 복잡도 높음',
        tags: [
          { label: '레시피 표준화', type: 'ok' },
          { label: '메뉴 수 많음', type: 'warn' },
          { label: '1인 운영 불가', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '4주 교육 받으면 혼자 돌려요.' },
          { dot: 'gold', text: '메뉴가 많아서 BHC보다 배울 게 많아요.' },
        ],
        qBtn: { label: '메뉴 많으면 운영이 얼마나 힘들어? →', target: 'sgyo9' },
      },
      {
        title: '경쟁 강도',
        hint: '주변 밀집도',
        val: '높음',
        valColor: 'red',
        row1Val: '반경 500m 내 4.8개',
        row1Label: '치킨집 전국 8.7만개',
        tags: [
          { label: '동일브랜드 500m 보호', type: 'ok' },
          { label: '타브랜드 무제한', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '같은 교촌은 500m 안에 못 열어요.' },
          { dot: 'gold', text: 'BBQ·BHC는 바로 옆도 가능해요.' },
        ],
        qBtn: { label: '보호구역 있어도 경쟁 심하다고? →', target: 'sgyo13' },
      },
      {
        title: '폐업 위험도',
        hint: '업계 통계 기반',
        val: '주의 필요',
        valColor: 'red',
        row1Val: '3년 내 폐업률 28%',
        row1Label: '오픈 6개월이 최대 위험',
        tags: [
          { label: '자금 소진 1위', type: 'warn' },
          { label: '입지 실패 2위', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '사전 준비가 생존을 결정해요.' },
          { dot: 'gold', text: '3년 안에 10명 중 3명 문 닫아요.' },
        ],
        qBtn: { label: '어디서 가장 많이 걸려서 망하나? →', target: 'sgyo13' },
      },
    ],
  },
  sgyo5: {
    brand: null,
    title: '얼마 드나?',
    sub: '총 2억 ~ 최대 2억 5천',
    breadcrumb: ['교촌', '얼마 드나?'],
    cards: [
      {
        title: '가맹비',
        hint: '계약 시 일시납',
        val: '1,000만원',
        valColor: 'yellow',
        row1Val: '1,000만원 일시납',
        row1Label: '5년 계약 · 갱신 시 재납부',
        tags: [
          { label: 'BHC보다 100만 비쌈', type: 'warn' },
          { label: '환불 조건 까다로움', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '1,000만 원, 교육비 200만 별도예요.' },
          { dot: 'gold', text: '1개월 지나면 못 돌려받아요.' },
        ],
        qBtn: { label: '교육비가 왜 따로 있어? →', target: 'sgyo13' },
      },
      {
        title: '인테리어',
        hint: '본사 지정업체 강제',
        val: '7,000만원',
        valColor: 'red',
        row1Val: '평당 약 350만원',
        row1Label: '20평 기준 · 5년마다 리모델링',
        tags: [
          { label: '본사 마진 25~35%', type: 'warn' },
          { label: '직접 업체 불가', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '20평 기준 7,000만 원이에요.' },
          { dot: 'gold', text: '본사 업체만 써야 해요. 직접 못 해요.' },
        ],
        qBtn: { label: '왜 직접 업체 쓰면 안 돼? →', target: 'sgyo13' },
      },
      {
        title: '장비/설비',
        hint: '주방 장비 일체',
        val: '5,000만원',
        valColor: 'red',
        row1Val: '5,000만원',
        row1Label: '튀김기·냉장·POS 포함',
        tags: [
          { label: '튀김기 3년 교체', type: 'warn' },
          { label: 'POS 350만', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '튀김기·냉장·POS 포함 5,000만이에요.' },
          { dot: 'gold', text: '소스 냉장고 따로 있어 BHC보다 비싸요.' },
        ],
        qBtn: { label: '3년마다 또 수천만이 나간다고? →', target: 'sgyo9' },
      },
      {
        title: '숨겨진 비용',
        hint: '보증금 + 예비금',
        val: '+5천 5백만+',
        valColor: 'red',
        row1Val: '최소 5,500만 추가',
        row1Label: '공개 금액 외 별도',
        tags: [
          { label: '보증금 2,500만~', type: 'warn' },
          { label: '예비금 3,000만', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '공개 금액 외에 5,500만 더 필요해요.' },
          { dot: 'gold', text: '2억만 보고 시작하면 3개월에 위기 와요.' },
        ],
        qBtn: { label: '돈 모자라면 정확히 어느 순간 망해? →', target: 'sgyo13' },
      },
    ],
  },
  sgyo9: {
    brand: null,
    title: '얼마 남나?',
    sub: '월 순이익 약 320만 (20평·직원1명)',
    breadcrumb: ['교촌', '얼마 남나?'],
    cards: [
      {
        title: '재료비',
        hint: '매출의 고정 비율',
        val: '-520만원',
        valColor: 'red',
        row1Val: '매출의 40% 고정',
        row1Label: '본사 공급 90% · 절감 불가',
        tags: [
          { label: '절감 여지 없음', type: 'warn' },
          { label: '매출 줄어도 고정', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '매출의 40%, 본사에서 90% 사야 해요.' },
          { dot: 'gold', text: '닭값 올라도 내가 그대로 써야 해요.' },
        ],
        qBtn: { label: '본사 공급 90%면 내 마음대로 못 해? →', target: 'sgyo13' },
      },
      {
        title: '인건비',
        hint: '직원 1명 기준',
        val: '-250만원',
        valColor: 'red',
        row1Val: '250만원 기본',
        row1Label: '주말 알바 +80만 추가 가능',
        tags: [
          { label: '1인 운영 불가', type: 'warn' },
          { label: '매년 상승', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '직원 1명 기준 250만 원이에요.' },
          { dot: 'gold', text: '메뉴 복잡해서 숙련된 직원이 필요해요.' },
        ],
        qBtn: { label: '메뉴 복잡해서 알바 구하기 어렵다고? →', target: 'sgyo13' },
      },
      {
        title: '임대료',
        hint: '20평 평균',
        val: '-150만원',
        valColor: 'yellow',
        row1Val: '평균 150만원',
        row1Label: '상권에 따라 50~500만 차이',
        tags: [
          { label: '200만 되면 반토막', type: 'warn' },
          { label: '권리금 별도', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: 'A급 상권 들어가고 싶은 브랜드예요.' },
          { dot: 'gold', text: '임대료 오르면 순이익이 바로 줄어요.' },
        ],
        qBtn: { label: '좋은 상권 들어가면 임대료가 얼마야? →', target: 'sgyo13' },
      },
      {
        title: '실제 순이익',
        hint: '모든 비용 제외 후',
        val: '약 320만원',
        valColor: 'yellow',
        row1Val: '약 320만원',
        row1Label: '매출 1,300만 · 직원 1명 기준',
        tags: [
          { label: '직원 2명 → 130만대', type: 'warn' },
          { label: '매출 1,600만 → 460만', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '매출 300만 올리면 순이익 44% 올라요.' },
          { dot: 'gold', text: '직원 한 명 더 쓰면 130만대로 줄어요.' },
        ],
        qBtn: { label: '월 320이면 투자금 회수에 몇 년 걸려? →', target: 'sgyo5' },
      },
    ],
  },
  sgyo13: {
    brand: null,
    title: '어디서 망하나?',
    sub: '오픈 6개월이 가장 위험한 구간',
    breadcrumb: ['교촌', '어디서 망하나?'],
    cards: [
      {
        title: '자금 소진',
        hint: '폐업 원인 1위',
        val: '35%',
        valColor: 'red',
        row1Val: '폐업의 35%',
        row1Label: '높은 초기비용이 직격탄',
        tags: [
          { label: '예비금 3천 필수', type: 'warn' },
          { label: '손익분기 5~7개월', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '망하는 이유 1위, 돈 먼저 바닥나요.' },
          { dot: 'gold', text: '2억 쓰고 손익분기에 5~7개월 걸려요.' },
        ],
        qBtn: { label: '손익분기까지 버티는 게 왜 이렇게 힘들어? →', target: 'sgyo5' },
      },
      {
        title: '입지 실패',
        hint: '폐업 원인 2위',
        val: '33%',
        valColor: 'red',
        row1Val: '폐업의 33%',
        row1Label: '사전 조사가 생존을 결정',
        tags: [
          { label: '배달vs홀 미스매치', type: 'warn' },
          { label: '조사 최소 3회', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '홀 손님 비중이 높은 브랜드예요.' },
          { dot: 'gold', text: '배달 상권에 홀 인테리어하면 망해요.' },
        ],
        qBtn: { label: '오픈하고 나면 입지는 못 바꾼다고? →', target: 'sgyo1' },
      },
      {
        title: '본사 갈등',
        hint: '계약 분쟁',
        val: '20%',
        valColor: 'yellow',
        row1Val: '폐업의 20%',
        row1Label: '계약서 안 보면 당함',
        tags: [
          { label: '단가 연 3~5% 강제 인상', type: 'warn' },
          { label: '메뉴 강제 변경', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '3사 중 본사 규정이 가장 빡빡해요.' },
          { dot: 'gold', text: '나가고 싶어도 위약금이 수천만이에요.' },
        ],
        qBtn: { label: '그만두고 싶어도 못 나온다고? →', target: 'sgyo5' },
      },
      {
        title: '번아웃 폐업',
        hint: '체력·정신 소모',
        val: '12%',
        valColor: 'yellow',
        row1Val: '폐업의 12%',
        row1Label: '주 7일 장시간 노동',
        tags: [
          { label: '1인 운영 시 고위험', type: 'warn' },
          { label: '1~2년 내 한계', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '메뉴 많아서 BHC보다 몸이 더 힘들어요.' },
          { dot: 'gold', text: '1~2년차에 체력 한계 오는 경우 많아요.' },
        ],
        qBtn: { label: '월 320 벌려고 주 7일 일하는 거 맞아? →', target: 'sgyo9' },
      },
    ],
  },
  sbbq0: {
    brand: '비비큐(BBQ)',
    title: '뭐가 궁금해?',
    sub: '핵심만 빠르게 파고드세요',
    breadcrumb: null,
    cards: [
      {
        title: '해볼 만할까?',
        brandKey: '비비큐(BBQ)',
        hint: '솔직한 한 줄 평가',
        val: '중상',
        valColor: 'yellow',
        row1Val: '종합 평가: 중상',
        row1Label: '브랜드 2위 · 프리미엄 전략 · 초기비용 높음',
        tags: [
          { label: '브랜드 2위', type: 'ok' },
          { label: '자금 2억+', type: 'warn' },
          { label: '객단가 높음', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '해외까지 나간 이름, 브랜드가 불러요.' },
          { dot: 'gold', text: '초기비용 높고 로열티 부담도 있어요.' },
        ],
        qBtn: { label: '프리미엄인데 왜 로열티가 부담이야? →', target: 'sbbq1' },
      },
      {
        title: '얼마 드나?',
        brandKey: '비비큐(BBQ)',
        hint: '초기 투자 현실적으로',
        val: '2억 내외',
        valColor: 'red',
        row1Val: '총 1억 9천~2억 5천',
        row1Label: '보증금·예비금 포함 시 최대 2.5억',
        tags: [
          { label: '가맹비 1,500만', type: 'warn' },
          { label: '인테리어 9천+', type: 'warn' },
          { label: '예비금 별도', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '총 1.9억~2.5억이에요.' },
          { dot: 'gold', text: '가맹비가 3사 중 제일 비싸요.' },
        ],
        qBtn: { label: '가맹비 1,500만이면 얼마나 비싼 거야? →', target: 'sbbq5' },
      },
      {
        title: '얼마 남나?',
        brandKey: '비비큐(BBQ)',
        hint: '한 달 실제 순이익',
        val: '약 340만',
        valColor: 'yellow',
        row1Val: '월 순이익 340만원',
        row1Label: '매출 1,400만 · 직원 1명 기준',
        tags: [
          { label: '재료비 -532만', type: 'warn' },
          { label: '인건비 -250만', type: 'warn' },
          { label: '로열티 -42만', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '잘 되면 한 달에 340만 남아요.' },
          { dot: 'gold', text: '재료비·로열티 합치면 실속이 적어요.' },
        ],
        qBtn: { label: '매출 1,400인데 순이익이 340뿐이야? →', target: 'sbbq9' },
      },
      {
        title: '어디서 망하나?',
        brandKey: '비비큐(BBQ)',
        hint: '폐업 패턴 분석',
        val: '가격저항 1위',
        valColor: 'red',
        row1Val: '가격저항 32%',
        row1Label: '프리미엄 가격에 소비자 이탈',
        tags: [
          { label: '가격저항 32%', type: 'warn' },
          { label: '입지 31%', type: 'warn' },
          { label: '자금소진 25%', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '비싼 상품이라 경기에 민감해요.' },
          { dot: 'gold', text: '불황 오면 BBQ부터 안 시켜요.' },
        ],
        qBtn: { label: '비싼 치킨 안 팔리면 어떻게 돼? →', target: 'sbbq13' },
      },
    ],
  },
  spura0: {
    brand: '푸라닭치킨',
    title: '뭐가 궁금해?',
    sub: '핵심만 빠르게 파고드세요',
    breadcrumb: null,
    cards: [
      {
        title: '해볼 만할까?',
        brandKey: '푸라닭치킨',
        hint: '솔직한 한 줄 평가',
        val: '중',
        valColor: 'yellow',
        row1Val: '종합 평가: 중',
        row1Label: '소자본 가능 · 인지도 낮음 · 틈새 전략',
        tags: [
          { label: '초기비용 낮음', type: 'ok' },
          { label: '브랜드 인지도↓', type: 'warn' },
          { label: '틈새 포지션', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '1억 미만으로 시작할 수 있어요.' },
          { dot: 'gold', text: '이름이 약해서 손님을 직접 모아야 해요.' },
        ],
        qBtn: { label: '인지도 낮으면 손님이 올까? →', target: 'spura1' },
      },
      {
        title: '얼마 드나?',
        brandKey: '푸라닭치킨',
        hint: '초기 투자 현실적으로',
        val: '1억 내외',
        valColor: 'yellow',
        row1Val: '총 9천~1억 2천만원',
        row1Label: '3대 브랜드 대비 40% 저렴',
        tags: [
          { label: '가맹비 500만', type: 'ok' },
          { label: '인테리어 5천~', type: 'neu' },
          { label: '예비금 별도', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '총 9천~1.2억, 3사보다 훨씬 싸요.' },
          { dot: 'gold', text: '싸게 시작해도 예비금은 꼭 있어야 해요.' },
        ],
        qBtn: { label: '싸게 시작하면 나중에 더 드는 거 아냐? →', target: 'spura5' },
      },
      {
        title: '얼마 남나?',
        brandKey: '푸라닭치킨',
        hint: '한 달 실제 순이익',
        val: '약 220만',
        valColor: 'yellow',
        row1Val: '월 순이익 220만원',
        row1Label: '매출 1,000만 · 직원 1명 기준',
        tags: [
          { label: '재료비 -380만', type: 'warn' },
          { label: '인건비 -250만', type: 'warn' },
          { label: '임대료 -120만', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '투자금 회수는 3사보다 빠를 수 있어요.' },
          { dot: 'gold', text: '매출이 작아서 절대 금액은 낮아요.' },
        ],
        qBtn: { label: '월 220만이면 너무 적은 거 아냐? →', target: 'spura9' },
      },
      {
        title: '어디서 망하나?',
        brandKey: '푸라닭치킨',
        hint: '폐업 패턴 분석',
        val: '집객 1위',
        valColor: 'red',
        row1Val: '집객 부족 40%',
        row1Label: '브랜드 인지도 부족이 직격탄',
        tags: [
          { label: '집객부족 40%', type: 'warn' },
          { label: '입지 30%', type: 'warn' },
          { label: '자금소진 20%', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '손님 모으는 게 가장 큰 숙제예요.' },
          { dot: 'gold', text: 'SNS·배달앱 광고 안 하면 빨리 망해요.' },
        ],
        qBtn: { label: '브랜드 힘 없이 어떻게 손님을 모아? →', target: 'spura13' },
      },
    ],
  },
  sbbq1: {
    brand: null,
    title: '해볼 만할까?',
    sub: '4가지 핵심으로 파악',
    breadcrumb: ['BBQ', '해볼 만할까?'],
    cards: [
      {
        title: '브랜드 파워',
        hint: '치킨 시장 인지도',
        val: '업계 2위',
        valColor: 'green',
        row1Val: '인지도 97%',
        row1Label: '재방문율 60% · 해외 50개국 진출',
        tags: [
          { label: '프리미엄 이미지', type: 'ok' },
          { label: '로열티 2~3%', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '황금올리브로 고급 이미지 만들었어요.' },
          { dot: 'gold', text: '로열티가 매달 2~3% 빠져나가요.' },
        ],
        qBtn: { label: '프리미엄 브랜드인데 왜 30%가 망해? →', target: 'sbbq13' },
      },
      {
        title: '초보자 난이도',
        hint: '시스템화 수준',
        val: '낮음',
        valColor: 'green',
        row1Val: '교육 3주 후 운영',
        row1Label: '매뉴얼 완성도 상',
        tags: [
          { label: '레시피 표준화', type: 'ok' },
          { label: '1인 운영 불가', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '3주 교육 받으면 혼자 돌려요.' },
          { dot: 'gold', text: '혼자서는 못 해요, 사람이 필요해요.' },
        ],
        qBtn: { label: '쉽다더니 왜 혼자는 못 하나? →', target: 'sbbq9' },
      },
      {
        title: '경쟁 강도',
        hint: '주변 밀집도',
        val: '높음',
        valColor: 'red',
        row1Val: '반경 500m 내 4.5개',
        row1Label: '치킨집 전국 8.7만개',
        tags: [
          { label: '동일브랜드 500m 보호', type: 'ok' },
          { label: '타브랜드 무제한', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '같은 BBQ는 500m 안에 못 열어요.' },
          { dot: 'gold', text: '비싼데 옆에 싼 치킨집 생기면 힘들어요.' },
        ],
        qBtn: { label: '비싼데 옆에 싼 치킨집 생기면? →', target: 'sbbq13' },
      },
      {
        title: '폐업 위험도',
        hint: '업계 통계 기반',
        val: '주의 필요',
        valColor: 'red',
        row1Val: '3년 내 폐업률 29%',
        row1Label: '오픈 6개월이 최대 위험',
        tags: [
          { label: '가격저항 1위', type: 'warn' },
          { label: '자금 소진 2위', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '소득 높은 상권에서는 잘 버텨요.' },
          { dot: 'gold', text: '3년 안에 10명 중 3명 문 닫아요.' },
        ],
        qBtn: { label: '어디서 가장 많이 걸려서 망하나? →', target: 'sbbq13' },
      },
    ],
  },
  sbbq5: {
    brand: null,
    title: '얼마 드나?',
    sub: '총 1억 9천 ~ 최대 2억 5천',
    breadcrumb: ['BBQ', '얼마 드나?'],
    cards: [
      {
        title: '가맹비',
        hint: '계약 시 일시납',
        val: '1,500만원',
        valColor: 'red',
        row1Val: '1,500만원 일시납',
        row1Label: '5년 계약 · 갱신 시 재납부',
        tags: [
          { label: '3사 중 가장 비쌈', type: 'warn' },
          { label: '환불 조건 까다로움', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '1,500만 원, 3사 중 가장 비싸요.' },
          { dot: 'gold', text: '계약 전 특약 조항 꼭 확인하세요.' },
        ],
        qBtn: { label: '계약 취소하면 돈 돌려받을 수 있어? →', target: 'sbbq13' },
      },
      {
        title: '인테리어',
        hint: '본사 지정업체 강제',
        val: '9,000만원',
        valColor: 'red',
        row1Val: '평당 약 450만원',
        row1Label: '20평 기준 · 5년마다 리모델링',
        tags: [
          { label: '본사 마진 25~35%', type: 'warn' },
          { label: '직접 업체 불가', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '20평 기준 9,000만 원이에요.' },
          { dot: 'gold', text: '3사 중 인테리어가 제일 비싸요.' },
        ],
        qBtn: { label: '9,000에 본사 마진이 포함됐다고? →', target: 'sbbq13' },
      },
      {
        title: '장비/설비',
        hint: '주방 장비 일체',
        val: '4,500만원',
        valColor: 'red',
        row1Val: '4,500만원',
        row1Label: '튀김기·냉장·POS 포함',
        tags: [
          { label: '튀김기 3년 교체', type: 'warn' },
          { label: 'POS 350만', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '튀김기·냉장·POS 포함 4,500만이에요.' },
          { dot: 'gold', text: '튀김기는 3년 되면 또 사야 해요.' },
        ],
        qBtn: { label: '3년마다 또 수천만이 나간다고? →', target: 'sbbq9' },
      },
      {
        title: '숨겨진 비용',
        hint: '보증금 + 예비금',
        val: '+5천만 이상',
        valColor: 'red',
        row1Val: '최소 5,500만 추가',
        row1Label: '공개 금액 외 별도',
        tags: [
          { label: '보증금 2,500만~', type: 'warn' },
          { label: '예비금 3,000만', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '공개 금액 외에 5,500만 더 필요해요.' },
          { dot: 'gold', text: '총 2.5억 준비해야 안전해요.' },
        ],
        qBtn: { label: '돈 모자라면 정확히 어느 순간 망해? →', target: 'sbbq13' },
      },
    ],
  },
  sbbq9: {
    brand: null,
    title: '얼마 남나?',
    sub: '월 순이익 약 340만 (20평·직원1명)',
    breadcrumb: ['BBQ', '얼마 남나?'],
    cards: [
      {
        title: '재료비',
        hint: '매출의 고정 비율',
        val: '-532만원',
        valColor: 'red',
        row1Val: '매출의 38% 고정',
        row1Label: '본사 공급 88% · 절감 불가',
        tags: [
          { label: '절감 여지 없음', type: 'warn' },
          { label: '매출 줄어도 고정', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '매출의 38%, 올리브유라 원가 높아요.' },
          { dot: 'gold', text: '본사에서 88% 사야 해서 줄일 수 없어요.' },
        ],
        qBtn: { label: '본사가 단가 올리면 내가 다 떠안아? →', target: 'sbbq13' },
      },
      {
        title: '인건비',
        hint: '직원 1명 기준',
        val: '-250만원',
        valColor: 'red',
        row1Val: '250만원 기본',
        row1Label: '주말 알바 +80만 추가 가능',
        tags: [
          { label: '1인 운영 불가', type: 'warn' },
          { label: '매년 상승', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '직원 1명 기준 250만 원이에요.' },
          { dot: 'gold', text: '최저임금 오를 때마다 같이 올라요.' },
        ],
        qBtn: { label: '혼자 다 하면 1~2년 안에 번아웃 온다고? →', target: 'sbbq13' },
      },
      {
        title: '로열티',
        hint: '매출의 고정 비율',
        val: '-42만원',
        valColor: 'yellow',
        row1Val: '매출의 3% 고정',
        row1Label: '3사 중 로열티 최고',
        tags: [
          { label: '매출 올라도 비율 고정', type: 'warn' },
          { label: '분쟁 시 인상 가능', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '매출의 3%, 3사 중 가장 높아요.' },
          { dot: 'gold', text: '매출 2,000만 되면 로열티만 60만이에요.' },
        ],
        qBtn: { label: '로열티 3%가 얼마나 큰 차이야? →', target: 'sbbq5' },
      },
      {
        title: '실제 순이익',
        hint: '모든 비용 제외 후',
        val: '약 340만원',
        valColor: 'yellow',
        row1Val: '약 340만원',
        row1Label: '매출 1,400만 · 직원 1명 기준',
        tags: [
          { label: '직원 2명 → 120만대', type: 'warn' },
          { label: '매출 1,700만 → 480만', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '잘 되면 한 달에 340만 남아요.' },
          { dot: 'gold', text: '불황 오면 매출이 확 빠지는 구조예요.' },
        ],
        qBtn: { label: '불황 오면 매출이 얼마나 빠져? →', target: 'sbbq13' },
      },
    ],
  },
  sbbq13: {
    brand: null,
    title: '어디서 망하나?',
    sub: '오픈 6개월이 가장 위험한 구간',
    breadcrumb: ['BBQ', '어디서 망하나?'],
    cards: [
      {
        title: '가격 저항',
        hint: '폐업 원인 1위',
        val: '32%',
        valColor: 'red',
        row1Val: '폐업의 32%',
        row1Label: '프리미엄 가격에 소비자 이탈',
        tags: [
          { label: '경기 민감도 높음', type: 'warn' },
          { label: '상권 선택 핵심', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '고급 상권에서는 잘 버텨요.' },
          { dot: 'gold', text: '불황 오면 3사 중 매출이 제일 빠져요.' },
        ],
        qBtn: { label: '어떤 상권이 BBQ에 맞아? →', target: 'sbbq1' },
      },
      {
        title: '입지 실패',
        hint: '폐업 원인 2위',
        val: '31%',
        valColor: 'red',
        row1Val: '폐업의 31%',
        row1Label: '상권 소득 수준 미스매치',
        tags: [
          { label: '저소득 상권 위험', type: 'warn' },
          { label: '조사 최소 3회', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '소득 높은 동네에서 해야 잘 돼요.' },
          { dot: 'gold', text: '서민 상권에서는 비싸서 안 팔려요.' },
        ],
        qBtn: { label: '오픈하고 나면 입지는 못 바꾼다고? →', target: 'sbbq1' },
      },
      {
        title: '자금 소진',
        hint: '초기 운영 위기',
        val: '25%',
        valColor: 'red',
        row1Val: '오픈 3개월차 최대 위험',
        row1Label: '초기 투자비 회수 기간 길어짐',
        tags: [
          { label: '예비금 3천 필수', type: 'warn' },
          { label: '대출이자 포함 계획', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '오픈 1~2개월은 손님이 몰려요.' },
          { dot: 'gold', text: '손익분기까지 5~7개월 버텨야 해요.' },
        ],
        qBtn: { label: '3개월 버티는 데 돈이 얼마나 필요해? →', target: 'sbbq5' },
      },
      {
        title: '본사 갈등',
        hint: '계약 분쟁',
        val: '12%',
        valColor: 'yellow',
        row1Val: '폐업의 12%',
        row1Label: '계약서 안 보면 당함',
        tags: [
          { label: '단가 연 2~4% 강제 인상', type: 'warn' },
          { label: '해지 조건 까다로움', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '메뉴·가격 다 본사가 정해요.' },
          { dot: 'gold', text: '나가고 싶어도 위약금이 수천만이에요.' },
        ],
        qBtn: { label: '그만두고 싶어도 못 나온다고? →', target: 'sbbq5' },
      },
    ],
  },
  spura1: {
    brand: null,
    title: '해볼 만할까?',
    sub: '4가지 핵심으로 파악',
    breadcrumb: ['푸라닭', '해볼 만할까?'],
    cards: [
      {
        title: '브랜드 파워',
        hint: '치킨 시장 인지도',
        val: '중하위',
        valColor: 'yellow',
        row1Val: '인지도 60%',
        row1Label: '재방문율 55% · 허브치킨 마니아층',
        tags: [
          { label: '마니아층 존재', type: 'ok' },
          { label: '자연 집객 약함', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '허브치킨 좋아하는 단골이 있어요.' },
          { dot: 'gold', text: '이름이 약해서 광고를 직접 해야 해요.' },
        ],
        qBtn: { label: '인지도 낮으면 오픈 초기 어때? →', target: 'spura13' },
      },
      {
        title: '초보자 난이도',
        hint: '시스템화 수준',
        val: '낮음',
        valColor: 'green',
        row1Val: '교육 2~3주 후 운영',
        row1Label: '메뉴 단순 · 매뉴얼 완성도 중상',
        tags: [
          { label: '레시피 표준화', type: 'ok' },
          { label: '소규모 운영 가능', type: 'ok' },
        ],
        insights: [
          { dot: 'teal', text: '2~3주면 혼자 돌릴 수 있어요.' },
          { dot: 'gold', text: '소규모라 혼자도 운영 가능해요.' },
        ],
        qBtn: { label: '소규모로 혼자 운영할 수 있어? →', target: 'spura9' },
      },
      {
        title: '경쟁 강도',
        hint: '주변 밀집도',
        val: '높음',
        valColor: 'red',
        row1Val: '반경 500m 내 4.2개',
        row1Label: '치킨집 전국 8.7만개',
        tags: [
          { label: '동일브랜드 500m 보호', type: 'ok' },
          { label: '3대 브랜드와 경쟁', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '같은 푸라닭은 500m 안에 못 열어요.' },
          { dot: 'gold', text: '3대 브랜드랑 싸워야 해서 더 힘들어요.' },
        ],
        qBtn: { label: '브랜드 약한데 경쟁에서 살아남으려면? →', target: 'spura13' },
      },
      {
        title: '폐업 위험도',
        hint: '업계 통계 기반',
        val: '주의 필요',
        valColor: 'red',
        row1Val: '3년 내 폐업률 33%',
        row1Label: '집객 실패가 최대 위험',
        tags: [
          { label: '집객 부족 1위', type: 'warn' },
          { label: '입지 실패 2위', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '초기비용 낮아서 손실이 작아요.' },
          { dot: 'gold', text: '3년 안에 10명 중 3명 문 닫아요.' },
        ],
        qBtn: { label: '어디서 가장 많이 걸려서 망하나? →', target: 'spura13' },
      },
    ],
  },
  spura5: {
    brand: null,
    title: '얼마 드나?',
    sub: '총 9천 ~ 최대 1억 2천',
    breadcrumb: ['푸라닭', '얼마 드나?'],
    cards: [
      {
        title: '가맹비',
        hint: '계약 시 일시납',
        val: '500만원',
        valColor: 'green',
        row1Val: '500만원 일시납',
        row1Label: '5년 계약 · 갱신 시 재납부',
        tags: [
          { label: 'BHC보다 400만 저렴', type: 'ok' },
          { label: '환불 조건 확인 필요', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '500만 원, 3사 중 가장 싸요.' },
          { dot: 'gold', text: '싼 만큼 본사 지원도 적은 편이에요.' },
        ],
        qBtn: { label: '가맹비 싸면 지원도 적은 거야? →', target: 'spura1' },
      },
      {
        title: '인테리어',
        hint: '본사 지정업체 강제',
        val: '5,000만원',
        valColor: 'yellow',
        row1Val: '평당 약 250만원',
        row1Label: '20평 기준 · 5년마다 리모델링',
        tags: [
          { label: '3사보다 40% 저렴', type: 'ok' },
          { label: '직접 업체 불가', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '20평 기준 5,000만 원이에요.' },
          { dot: 'gold', text: '직접 업체 사용은 안 돼요.' },
        ],
        qBtn: { label: '5년 후 리모델링 비용도 똑같이 나와? →', target: 'spura13' },
      },
      {
        title: '장비/설비',
        hint: '주방 장비 일체',
        val: '3,500만원',
        valColor: 'yellow',
        row1Val: '3,500만원',
        row1Label: '튀김기·냉장·POS 포함',
        tags: [
          { label: '튀김기 3년 교체', type: 'warn' },
          { label: 'POS 250만', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '소규모 매장이라 장비도 적어요.' },
          { dot: 'gold', text: '튀김기는 3년 되면 또 사야 해요.' },
        ],
        qBtn: { label: '장비 싸면 품질도 다른 거야? →', target: 'spura1' },
      },
      {
        title: '숨겨진 비용',
        hint: '보증금 + 예비금',
        val: '+3천만 이상',
        valColor: 'yellow',
        row1Val: '최소 3,000만 추가',
        row1Label: '공개 금액 외 별도',
        tags: [
          { label: '보증금 1,500만~', type: 'warn' },
          { label: '예비금 2,000만', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '공개 금액 외에 3,000만 더 필요해요.' },
          { dot: 'gold', text: '이 돈 없으면 3~4개월에 바닥나요.' },
        ],
        qBtn: { label: '1억 미만으로 진짜 창업 가능해? →', target: 'spura13' },
      },
    ],
  },
  spura9: {
    brand: null,
    title: '얼마 남나?',
    sub: '월 순이익 약 220만 (15평·직원1명)',
    breadcrumb: ['푸라닭', '얼마 남나?'],
    cards: [
      {
        title: '재료비',
        hint: '매출의 고정 비율',
        val: '-380만원',
        valColor: 'red',
        row1Val: '매출의 38% 고정',
        row1Label: '본사 공급 80% · 절감 여지 소폭',
        tags: [
          { label: '절감 여지 제한적', type: 'warn' },
          { label: '허브재료 단가 높음', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '본사 의존도 낮아 일부 직접 구매 가능해요.' },
          { dot: 'gold', text: '허브 재료 비싸서 원가가 높은 편이에요.' },
        ],
        qBtn: { label: '허브재료 비싸면 원가가 더 높아? →', target: 'spura13' },
      },
      {
        title: '인건비',
        hint: '직원 1명 기준',
        val: '-200만원',
        valColor: 'yellow',
        row1Val: '200만원 기본',
        row1Label: '소규모 매장 · 파트타임 활용 가능',
        tags: [
          { label: '소규모 운영 유리', type: 'ok' },
          { label: '매년 상승', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '파트타임으로 돌릴 수 있어요.' },
          { dot: 'gold', text: '직원 1명 기준 200만 원이에요.' },
        ],
        qBtn: { label: '파트타임으로 운영하면 품질 유지돼? →', target: 'spura1' },
      },
      {
        title: '임대료',
        hint: '15평 평균',
        val: '-120만원',
        valColor: 'green',
        row1Val: '평균 120만원',
        row1Label: '소규모 매장 · 임대료 부담 낮음',
        tags: [
          { label: '소규모 상권 가능', type: 'ok' },
          { label: '권리금 별도', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '소규모라 임대료가 낮아요.' },
          { dot: 'gold', text: '상권 따라 매출 차이가 많이 나요.' },
        ],
        qBtn: { label: '주택가에서도 장사가 돼? →', target: 'spura1' },
      },
      {
        title: '실제 순이익',
        hint: '모든 비용 제외 후',
        val: '약 220만원',
        valColor: 'yellow',
        row1Val: '약 220만원',
        row1Label: '매출 1,000만 · 직원 1명 기준',
        tags: [
          { label: '직원 2명 → 50만대', type: 'warn' },
          { label: '매출 1,300만 → 350만', type: 'neu' },
        ],
        insights: [
          { dot: 'teal', text: '투자금 회수는 3사보다 빠를 수 있어요.' },
          { dot: 'gold', text: '직원 한 명 더 쓰면 50만대로 줄어요.' },
        ],
        qBtn: { label: '월 220인데 투자금 회수에 몇 년 걸려? →', target: 'spura5' },
      },
    ],
  },
  spura13: {
    brand: null,
    title: '어디서 망하나?',
    sub: '오픈 6개월이 가장 위험한 구간',
    breadcrumb: ['푸라닭', '어디서 망하나?'],
    cards: [
      {
        title: '집객 부족',
        hint: '폐업 원인 1위',
        val: '40%',
        valColor: 'red',
        row1Val: '폐업의 40%',
        row1Label: '브랜드 파워 부재로 직격탄',
        tags: [
          { label: 'SNS 마케팅 필수', type: 'warn' },
          { label: '배달앱 광고비 부담', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '직접 마케팅하면 충성 손님이 생겨요.' },
          { dot: 'gold', text: 'SNS·배달앱 안 하면 손님이 안 와요.' },
        ],
        qBtn: { label: '마케팅 안 하면 얼마나 빨리 망해? →', target: 'spura9' },
      },
      {
        title: '입지 실패',
        hint: '폐업 원인 2위',
        val: '30%',
        valColor: 'red',
        row1Val: '폐업의 30%',
        row1Label: '유동인구 없는 상권 오픈',
        tags: [
          { label: '배달 상권 필수', type: 'warn' },
          { label: '조사 최소 3회', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '배달 많이 시키는 동네가 맞아요.' },
          { dot: 'gold', text: '브랜드 약하니까 자리가 더 중요해요.' },
        ],
        qBtn: { label: '오픈하고 나면 입지는 못 바꾼다고? →', target: 'spura1' },
      },
      {
        title: '자금 소진',
        hint: '초기 운영 위기',
        val: '20%',
        valColor: 'yellow',
        row1Val: '오픈 3~4개월차 위험',
        row1Label: '집객 안 되면 예비금 빠르게 소진',
        tags: [
          { label: '예비금 2천 필수', type: 'warn' },
          { label: '마케팅비 예산 확보', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '초기비용은 3사보다 적어요.' },
          { dot: 'gold', text: '손님 안 오면 예비금이 빨리 없어져요.' },
        ],
        qBtn: { label: '예비금 없으면 언제 망해? →', target: 'spura5' },
      },
      {
        title: '번아웃 폐업',
        hint: '체력·정신 소모',
        val: '10%',
        valColor: 'yellow',
        row1Val: '폐업의 10%',
        row1Label: '마케팅+운영 이중 부담',
        tags: [
          { label: '마케팅 직접 해야 함', type: 'warn' },
          { label: '운영+홍보 이중 소모', type: 'warn' },
        ],
        insights: [
          { dot: 'teal', text: '조리 자체는 단순해서 몸은 덜 힘들어요.' },
          { dot: 'gold', text: 'SNS까지 혼자 하면 머리가 지쳐요.' },
        ],
        qBtn: { label: '월 220 벌려고 이 고생을 해야 해? →', target: 'spura9' },
      },
    ],
  },
}
